### ISSUE TITLE
Allow opening menu items in new browser tab

### ISSUE THREAD

**Issue by coberleyv** [SAP/luigi#1032]
Luigi menu items currently have an href content of "javascript:void(null)" which prevents the link from being opened in a new browser tab. Users can reasonable expect that a menu item can be opened in a new tab, since browsers provide the context menu "open in new tab". Instead, users will experience a new blank tab being opened with the title "about:blank#blocked", which makes for a bad experience. For business users, it can be quite useful to open different menu items simultaneously, for instance, one tab open for the configuration of an item, and one tab for reports related to that item. (FYI, I am a product owner on an SAP product, and this request arose as a discussion from our UX/PM team)

**Comment by corey-aloia** [comment]
@JohannesDoberer I see that this was closed without and comment or PR attached... anyway you can confirm that this was implemented?

**Comment by maxmarkus** [comment]
@corey-aloia it is done in the connected PR SAP/luigi#1034 and available in the latest release.
Are you not able to see the _ maxmarkus connected this issue to SAP/luigi#1034 Add valid href to navigation links on 7 Jan_  ?

**Comment by corey-aloia** [comment]
@maxmarkus, I am not able to see this
