### ISSUE TITLE
Feature Request: Partial navigation node matching with url propagating between iframe and shell

### ISSUE THREAD

**Issue by Algatron** [SAP/luigi#1038]
## Summary
As a Luigi framework user, I want to define navigation configuration nodes **only for visible menu entries**, and/or maybe some root paths that are navigate-able using Luigi navigation APIs.
**- and -**
As a Luigi framework user, I want to be able to continue using the navigation mechanism from my framework of choice in the micro frontend (ex: routerLink from angular) and have this url being updated in the shell address bar (for bookmarking, refreshing).

## Background
Currently all navigation flows in 1 direction, using Luigi API to navigate, Luigi Core will map pathSegments provided to a view url and load it in the iframe. Any url changes (outside of Luigi navigation) in the iframe will not be propagated to the parent frame.

This causes 2 major unwanted side effects

1. I am forced to define a ton of nodes that are not visible in the menu, but just to allow navigation API to accept the navigation request.

2. I am forced the discard all navigation mechanisms, or at least enhance them so that they also trigger a navigation from Luigi API

## Technical
I've bounced a few ideas around with @maxmarkus, I'm sure he knows a lot better than I what solution might work best given the Luigi implementation, but it seem like we could enhance the navigation structure, maybe with have some kind of new  flag on a node to indicate that this is some kind of **root** path, and that anything after this in the URL should be appended to some view url, and likewise Luigi-Client could detect location changes in the iframe, and push this to the Luigi-Core which could then kind of do a reverse lookup, and apply the trailing URL to the address bar.

I think something like this would be sufficient, and work, however... 
## More of a philosophical thing maybe?

I find that combining the visible nodes for the menu navigation, with the navigate-able paths to be a bit of a mix of concerns. I think the the visual representation of the menu should not have anything to do with where you can actually navigate.

For example if I have a micro-frontend with paths:
```
/a
/a/b
/a/b/c
/a/b/d
```
but in the future I know that the team that owns this micro-frontend will add more paths that are not visible in the menu. In this case I don't want to have to define new nodes when they implement new features, I just want those paths to work out of the box.
I just want to tell Luigi that /a is kind of a base URL. Anything after that should be propagated to the iframe url, and in reverse, any iframe url suffix should be appended to the address bar, for bookmarking, refresh etc...
Then defining the visual elements to say /a and /a/b/c would be separate and accepted since they start with this know /ab base url anyway.

If you stick with a simple review lookup of viewUrl as being a prefix to the url in the iframe, then things like duplicate viewUrl will be an issue.

**Comment by maxmarkus** [comment]
Available now in version 0.7.6:
node: `virtualTree`: https://docs.luigi-project.io/docs/navigation-parameters-reference/?section=virtualtree
and 
linkManager: `withoutSync` https://docs.luigi-project.io/docs/luigi-client-api/?section=withoutsync
