### ISSUE TITLE
Externalize auth providers

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1039]
In order to further strip down our footprint for luigi core package, current "standard" auth providers should be removed from core and shipped as dedicated packages. Since this will be a breaking change, it should be released with 1.0.0

**Comment by maxmarkus** [comment]
I created a fork of OAuth2 Provider and it works with lerna in my angular example :-) https://github.com/maxmarkus/luigi-plugin-auth-oauth2
It uses the exact same setup as Luigi Client build pipeline. Proposed new naming schema: _@luigi-project/plugin-auth-oauth2_

OpenIdConnect will follow and is a bit more work.
