### ISSUE TITLE
Investigate pipeline issues in travis

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1085]
Issue opened at travis community. https://travis-ci.community/t/cypress-chrome-all-build-broken-at-same-time/7166
It looks like Chrome 80 is the issue.

**Comment by JohannesDoberer** [comment]
We have to clear the cache in travis all the time

**Comment by maxmarkus** [comment]
Chrome 80 fails with Cypress, applied for debug mode:
https://docs.travis-ci.com/user/running-build-in-debug-mode/
