### ISSUE TITLE
Reinitialising Luigi  HTML container dynamically

### ISSUE THREAD

**Issue by sebastienbarbier** [SAP/luigi#1126]
**Description**

My Luigi container is part of an angular application with a login/logout process. On login, a user initialise luigi and has successfully access to the app. On logout it destroy the HTML container from the DOM to show the login form. 
If the user login a second time, we display the luigi container again but it no longer start. On page reload, luigi load properly.

I am looking for a way to reinitialise the HTML container, losing the previous instance would actually be acceptable but I believe Luigi should be able to reload.

**Expected result**

Luigi should appear on the second load.

**Actual result**

Luigi do not appear at all.

**Steps to reproduce**

You can access the [stackblitz angular-luigi-routing](https://stackblitz.com/edit/angular-luigi-routing) I just created which display a luigi container within two angular pages. 
My use case is exactly the one when switching to the login page then back to the luigi page using the navigation menu on top of the app.

**Troubleshooting**

Starting Luigi using `Luigi.setConfig`, on second load I could see the initialise value is set to true and so I guess skip the binding with the DOM. If it is false, it works.

**Comment by sebastienbarbier** [comment]
After direct chat on slack, my use case works perfectly if I add `Luigi.initialized = false` before `setConfig ` 👍. 

This solution **feels to me like a hack** more than a feature, editing boolean state directly might have unexpected side effect I might now know about. I guess as a dev, I would feel better by **having a specific function/event/piece of code** to call 🙌.

**Comment by anshul77** [comment]
When i am trying to compile the project of stackblitz in luigi component i got the error Cannot find name 'Luigi'. Can anyone tell how to resolve it? Or how to use Luigi object in a ts file
