### ISSUE TITLE
Getting notified of unresponsive Luigi clients

### ISSUE THREAD

**Issue by kuhris** [SAP/luigi#1127]
**Description**

It would be nice if Luigi provided a feature that notifies the core if one of the clients fails to load or becomes unresponsive.

**Reasons**

We are starting to embed external pages into our application and would like to handle this kind of scenario, for example by redirecting the user to an error page.

**Comment by JohannesDoberer** [comment]
- add pageErrorHandler to navigation nodes containing timout, errorpage url and errorfn
- add it to defaults mechanism, like isolate view
