### ISSUE TITLE
Investigate a JS way of providing config for fiddle e2e

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#1243]
In e2e tests for fiddle, sending "stringified" config to fiddle is not optimal since the config might contain functions  such as  customRenderer which [cannot be stringified](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) .
Find a solution that avoids strings and uses a js config file/object instead.

**Comment by maxmarkus** [comment]
One idea which came to my mind:

    var sNew = document.createElement("script");
    sNew.async = true;
    sNew.src = "path/to/config.js";
    var s0 = document.getElementsByTagName('script')[0];
    s0.parentNode.insertBefore(sNew, s0);
    ​
    var intv = setInterval(function() {
        if(window.config) {
            console.log('config', window.config)
            Luigi.setConfig(window.config)
            clearInterval(intv)
        }
    }, 100)

This would work, if we provide the configurations properly. Check if `require()` statements work, so we can have a base that we enrich then with the example data.
