### ISSUE TITLE
GitHub security alert

### ISSUE THREAD

**Issue by zarkosimic** [SAP/luigi#1256]

**Comment by zarkosimic** [comment]
- `tough-cookie` is sub dependency of `async-request`. Since `async-request` is already updated to the last version I was not able to update `tough-cookie` on this way. 
The last version of `async-request` has been published 5 years ago. I don't believe the new version gonna be soon. 

- A possible solution would be to replace `async-request` with one of the alternatives.

<img width="212" alt="Screenshot 2020-04-09 at 19 42 55" src="https://user-images.githubusercontent.com/42171300/78927817-cc0cc880-7a9f-11ea-85fd-38630a7c1b74.png">

**Comment by JohannesDoberer** [comment]
We will ignore this, because we do not use this functionality.
