### ISSUE TITLE
Docu: Search docu by clicking keyword labels

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#1274]
Followup of #1273

With a click on a keyword, docu search should get triggered with that keyword.
Clickable state adds a shadow to the label.

<img width="649" alt="screen markus e 2020-04-16 at 11 25 13" src="https://user-images.githubusercontent.com/1720843/79441654-ce0ee400-7fd7-11ea-93d5-41fafedee42e.png">

**Comment by JohannesDoberer** [comment]
Fixed in #1690
