### ISSUE TITLE
PageErrorHandler doesnt redirect to  mentioned path if microfrontend fails with "X-frame-options:sameorigin" error

### ISSUE THREAD

**Issue by mayankgupta0510** [SAP/luigi#1308]
Hi,
 I wanted to redirect to specific page if microfrontend fails with any error (but specifically I am looking for X-Frame-options error).
so in my example : if I navigate to "/extension" then it should load the microfrontend and ifmicrofront has X-frame-options : sameorigin then it should redirect to my specified path i.e. 
"/extension.html" page 
let me know if I have missed anything here.

below is my Luigi-config : 

Luigi.setConfig({
    navigation: {
        contextSwitcher : {
            defaultLabel: 'Select Subdomain',
            parentNodePath: '/extension', // absolute path
            lazyloadOptions: true, // load options on click instead on page load
            options: () =>
                [...Array(2).keys()]
                .filter(n => n !== 0)
                .map(n => ({
                label: 'i077549-dev', // (i.e mapping between what the user sees and what is taken to replace the dynamic part for the dynamic node)
                pathValue: '?~subdomain=i077549-dev' // will be used to replace dynamic part
            }))
      },
        
        nodes: [{
            pathSegment: 'home',
            hideFromNav: true,
            hideSideNav: true,
            viewUrl: '/newhome.html',
            loadingIndicator: {
            enabled: false,
            pageErrorHandler: {
                timeout: 3,
                errorFn: () => _utils.setWindowLocationHref('extension')
            }
          }
        },{
          pathSegment: 'extension',
          hideFromNav: true, 
          hideSideNav: true,
          loadingIndicator: {
            enabled: false
          },
        onNodeActivation : function(){
            console.log("Node Activated");
        },
          pageErrorHandler: {
                timeout: 3,
                redirectPath: '/extension.html#subdomain={nodeParams.subdomain}'
          },
          viewUrl: 'https://sap-cloud-platform-home-i077549-dev-development-saptest.cfapps.sap.hana.ondemand.com/'
        }],
      appSwitcher :{
        showMainAppEntry: true,
        items: [
          {
            title: 'Extension suite',
            link: '/extension'
          },
        ]
      }
            
    },
    routing: {
        useHashRouting: false,
        nodeParamPrefix: '~'
    },
    settings: {
        responsiveNavigation: 'Fiori3',
        header: {
            title: 'SAP Cloud Platform Home'
        },
        customSandboxRules: ['allow-top-navigation'],
        iframeCreationInterceptor: (iframe, viewGroup, navigationNode, microFrontendType) => {
            if (microFrontendType !== 'modal')
                iframe.allowFullscreen = true;
            }
    }

I have an microfrontend : "https://sap-cloud-platform-home-i077549-dev-development-saptest.cfapps.sap.hana.ondemand.com/’"

**Comment by marynaKhromova** [comment]
We should add to the documentation that the PageErrorHandler works only if loading indicator is not disabled.
