### ISSUE TITLE
Programmatically test the examples

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#1323]
Install the examples and test them one after another:

1. Execute scripts/setup/<name>.sh with & in the background
2. Check if the webserver is running, once this is ok
3. Run the cypress test which opens the page and checks if an iframe exists
4. Kill webserver
5. Remove the install folder
6. Continue with the next setup script

Add the job to Travis to be run after merging to master as a separate running instance.

**Comment by JohannesDoberer** [comment]
Config a cronjob and run it once a week.

**Comment by viktorsperling** [comment]
Will close this issue next Monday, after the tests were triggered accordingly.
