### ISSUE TITLE
pageNotFoundHandler redirectTo triggers route change twice on angular 1

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#1347]
AngularJS (maybe applies to other routers too) receives two redirect events if it is executed in the same loop. 
@kistll was able to reduce it to one event by adding a setTimeout at the generic asyncGenerator. It seems the initial and redirect event are triggered in the same loop. Still it needs to be debugged if this is really the issue.

Angularjs route changes look like: 
/mmmmmm
/notfound
/mmmmmm
/notfound

```javascript
public pageNotFoundHandler() {
  return { redirectTo: '/notfound'};
}
```

```javascript
skipRoutingForUrlPatterns = [
  /access_token=/,
  /id_token=/,
  /#\/notfound
]
```

**Comment by JohannesDoberer** [comment]
Waiting for customer response.

**Comment by maxmarkus** [comment]
Got response and can be closed.
