### ISSUE TITLE
How can I style the Luigi core elements?

### ISSUE THREAD

**Issue by huberv** [SAP/luigi#1352]
**Description**

From reading the documentation I would say that the css styles are embedded in the Luigi core. This is fine as long as you are using one of the Fiori Fundamentals libaries, but what about using Luigi with e.g. Google's material design? Is there a way to style Luigi in a consistent and future-proof way?

**Reasons**

I guess Luigi shouldn't be tied to the SAP Fiori Fundamentals libraries / styles.

**Comment by hardl** [comment]
Hi,
there are several options at the moment:
1) use fundamental styles theming capabilities, see also https://github.com/SAP/theming-base-content, you can already achieve a lot by customizing the css variables
2) manually overwrite the styles where needed, you can check our documentation app as an example (yes, it is a luigi app ;) )
3) turn off luigi view components completely and implement your own view components for header and navigation

Cheers

**Comment by huberv** [comment]
Hi Philipp,

Thanks for the swift reply! It would be great to have options 1 and 3 in the official documentation.

**Comment by hardl** [comment]
There will be comprehensive examples soon showing how it is done (https://github.com/SAP/luigi/issues/1361)
In general, you just define your custom html components as usual (you are owning index.html) and connect them to luigi via luigi core api
