### ISSUE TITLE
Create React core app for SAP Tutorials

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#1388]
Create the core of our tutorials app: a simple shopping app which showcases Luigi capabilities. For more details, check https://cxwiki.sap.com/display/luigi/Luigi+SAP+Tutorials

**Comment by stanleychh** [comment]
Pull Request: https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1
