### ISSUE TITLE
Create UI5 micro frontend for SAP Tutorials

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#1389]
Create a UI5 micro frontend for Luigi tutorials. The tutorial app is a simple shopping app which showcases Luigi capabilities. For more details, check https://cxwiki.sap.com/display/luigi/Luigi+SAP+Tutorials

**Comment by stanleychh** [comment]
Pull Request: https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1

**Comment by hardl** [comment]
Review summary:
* Add SAP logo as header logo
* enrich README.md in ui mfe
* change locales to official tags, like 'de-DE' (currently it is 'Deutsch') 
* product details page shows a red alert for some milliseconds, i assume it is the same as if you open it with a wrong product id. please hide this until you know that the product really doesn't exist.

**Comment by stanleychh** [comment]
A new [Pull Request](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/3) which fixed above issues. Also provided i18n at micro frontend apps.

**Comment by hardl** [comment]
LGTM 👍
