### ISSUE TITLE
BadgeCounter enhancements

### ISSUE THREAD

**Issue by azriel46d** [SAP/luigi#1407]
**Description**
1. `badgeCounter` on the side menu
    - The badge counter is already listed for navigation items, just a small enhancement to the side menu would increase flexibility.
<img width="158" alt="Screenshot 2020-06-12 at 17 49 07" src="https://user-images.githubusercontent.com/2339134/84522192-7ab6ca80-acd6-11ea-8a08-4aeeeec7c5ec.png">

**Comment by ndricimrr** [comment]
Merged ✅ . Thanks for your contribution 😃  @azriel46d
