### ISSUE TITLE
How can I use Luigi core as a library in my own UI?

### ISSUE THREAD

**Issue by webdevan** [SAP/luigi#1408]
Sorry if this has been answered, but I couldn't find it in the docs.

I want to build my own app shell (complete with custom site header, menu, toast messages, etc) and use Luigi as a JS library to manage the routing and iframe portion. I'd like my own menu component to trigger route changes and my toast alerts to subscribe to Luigi errors.

From what I can gather the examples all include a built-in app shell/UI but I want to make my own UI and just leverage the iframe routing and other features in Luigi. Is this not possible?

**Comment by maxmarkus** [comment]
Hello @webdevan
This is possible already :-) 
Please check the [FAQ](https://docs.luigi-project.io/docs/faq) section **I don't want to use the default Fiori Fundamentals style. How can I style Luigi differently?**

**Comment by webdevan** [comment]
Thanks @maxmarkus. So the answer is basically to set hideNavigation to true and use the core API in your own UI components. Perhaps a "getting started" example of this would help people like me find the solution more easily. I'll see if I can contribute in this regard when I get around to building something.

**Comment by hardl** [comment]
Hi @webdevan, you are absolutely right. We have an epic for this here: https://github.com/SAP/luigi/issues/1361
Contribution is highly appreciated ;) Maybe you can contact us via our slack workspace for sharing more details
