### ISSUE TITLE
Content security policy issues on Luigi

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1449]
Description from a customer:

> Luigi uses eval in the JS code as well as inline styles. These two solutions are considered as unsafe by CSP, as we all know.
> The problem is that you can allow or not to execute certain script in many ways but you can’t control the content of the script. In our case the luigi.js script is executed properly (via nonce directive) but we still have to globally allow unsafe-eval because of its content.
> The best solution would be to allow unsafe-eval just for this particular script but, as I said before, it’s impossible to be done via CSP.

linked issue: https://github.tools.sap/kyma/backlog/issues/129

**Comment by ndricimrr** [comment]
As we are not using eval directly in our code, it seems to be an issue related to compiled luigi code instead (also pointed out by @parostatkiem in the luigi general channel on slack), meaning this is most probably something to do with webpack configurations.

Some really good references with the same issue in place that are worth giving it a try: 
[How to remove eval and Function constructor from webpack build to avoid CSP issues]
(https://stackoverflow.com/questions/48695579/how-to-remove-eval-and-function-constructor-from-webpack-build-to-avoid-csp-issu)

The same question asked in an issue on webpack repo: 
[How to remove eval and Function constructor from webpack build to avoid CSP issues](https://github.com/webpack/webpack/issues/6461)

Hopefully this should be fixed through tweaking some configurations. 

Alternative sources if first source doesn't work : 
[Webpack Babel-loader transpiles code with eval()
](https://stackoverflow.com/questions/50358773/webpack-babel-loader-transpiles-code-with-eval)

**Possible follow-up issue for this one:**
In the future we need to educate devs not to use *eval* in their code. A new task to be created after this one to add some hook that checks the code for any usages of *eval*

**Comment by ndricimrr** [comment]
Current Updates: Changing webpack configurations doesn't seem to effect the Function constructor functions. 

Could be related to Svelte loader instead. 
Will check
[Svelte Content Security Policy (CSP)](https://sapper.svelte.dev/docs#Content_Security_Policy_CSP)

Also worth looking into https://www.w3.org/TR/CSP3/#directive-script-src  and an answer [here](https://stackoverflow.com/questions/52573756/what-are-the-eval-related-functions-to-be-avoided-when-csp-is-enabled). It could be that CSP can also complain for other functions as well. WIl look into it

**Comment by ndricimrr** [comment]
Decided to create two new separate tickets for `unsafe-eval` and `unsafe-inline`

**Comment by parostatkiem** [comment]
Any updates on this? We're waiting for it in Kyma 😃

**Comment by hardl** [comment]
We were able to reduce the amount of occurences by tweaking webpack/babel config, but not to completely get rid of them... yet. Still working on it.

**Comment by ndricimrr** [comment]
This will solve the unsafe-inline for scripts and unsafe-eval related csp issue. However, we have accepted the unsafe-inline for style-src , being that we rely on some inline styles for configurable sizes like modals and more.
