### ISSUE TITLE
Write test scenarios based on luigi application

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1475]
- Apply the latest build of [Luigi core](@luigi-project/core) and [Luigi client](https://www.npmjs.com/package/@luigi-project/client) to application
- Put (valid) nodes on top, left nav and test these scenarios by cypress
- Integrate with Travis CI
- Setup nightly build

**Comment by stanleychh** [comment]
Commits: https://gitlab.com/team-phteven/luigi-e2e-application/-/commits/master
Travis CI: https://travis-ci.com/gitlab/team-phteven/luigi-e2e-application/builds
