### ISSUE TITLE
Fix versioning of the left side nav

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/luigi#1505]
Currently, we have Luigi v1.3.0 and in the footer of the side nav it says Luigi Client 1.0.0
![Screen Shot 2020-07-22 at 11.45.44.png](https://images.zenhubusercontent.com/5e85ddcb5fc38b158b99e42a/126e8f22-2b70-4d43-ae69-81ec540e74bf)

**Comment by maxmarkus** [comment]
The configuration is just reading what you have installed:
`import { version } from '../../../node_modules/@luigi-project/client/package.json';`

According to the [docs](https://github.com/SAP/luigi/blob/master/test/e2e-test-application/README.md#development), devs should not run `npm i`, but always `lerna bootstrap --force-local` to install dependencies, which links the latest local bundle to the e2e application.
