### ISSUE TITLE
Adapt blog behaviour when there is more than 3/5 blogs on the overview page

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/luigi#1506]
Would be great to have a concept in advance which allows seeing the list of all blogs on the overview page nicely. 

A proposal to use "Load more"- pattern for every 5 additional blogs. Similar to this one: https://blog.adobe.com/

When there is no more blog posts hiding the button "load more" and showing the button "Back to top".
"Back to top" button will lead a user to the top of the page.

On page re-load the blogs return to the initial state

**Comment by JohannesDoberer** [comment]
First:
Clarify how the implementation would look like.
