### ISSUE TITLE
Does this support Nextjs?

### ISSUE THREAD

**Issue by xmkan** [SAP/luigi#1540]
Hi just wish to check if this library support Nextjs and is there sample/example codes for it?

**Comment by JohannesDoberer** [comment]
Hi,
thanks for the request.
We have a [ticket](https://github.com/SAP/luigi/issues/1122) in the current sprint where we try to provide a solution and an example how to use Luigi based on nextjs.

**Comment by JohannesDoberer** [comment]
Closing as duplicated.
