### ISSUE TITLE
Create Luigi tutorials on SAP platform

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#1551]
Before we can publish tutorials on **developers.sap.com**, there is a test (QA) system at **developers-qa.sap.com** where we can see what the tutorials would look like, and where SAP can eventually review and approve them.

Tutorials based on Stanley's [steps](https://app.zenhub.com/files/139590701/49896ab7-76dc-4f37-9559-8d7e1199aa23/download):

https://developers-qa.sap.com/tutorials/luigi-app-basic-setup.html
https://developers-qa.sap.com/tutorials/luigi-app-configuration.html

Credentials:
username: wcms
password: wcms

There are also GitHub commits for the tutorials, but as there are no separate branches on that repo, it can be hard to find the right commits. Try searching for "luigi". 
https://github.com/SAPDocuments/Tutorials-Contribution/commits/master

**Comment by ndricimrr** [comment]
Small change regarding Line 11 and 12. Check [the latest commit/latest version](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1/commits/3747cbac86abe0306726fa7092a14713fc91f819) in the PR. Just thought to have some consistency between the PR and the tutorial :) 

![Screenshot 2020-08-17 at 10.09.00.png](https://images.zenhubusercontent.com/5ddce54970febb0001f9c812/c576c738-90c1-4205-9cd1-52b19ebc4a68)

**Comment by stanleychh** [comment]
thanks @ndricimrr . @alexandra-simeonova , I forgot to inform you this change. The two scripts were wrapped in body tag.

**Comment by alexandra-simeonova** [comment]
It's updated, thank you :)

**Comment by stanleychh** [comment]
@alexandra-simeonova  , there was a small config missing from the steps I sent you. Please add [this part](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1/commits/6df15b0ad32767fd43658121bb5607d936f0c95d#diff-43425cbc584230cd90dd7260a49950edR14-R18) into [step 12th](https://developers-qa.sap.com/tutorials/luigi-app-configuration.html#1e9d5d72-a4cc-40c9-a05e-eb10b75f0bda). Thanks

**Comment by stanleychh** [comment]
A small improvement of [step 14th](https://developers-qa.sap.com/tutorials/luigi-app-configuration.html#92dcc9f2-2940-4f3e-b71f-a681edb7ceb5), according to [this change](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1/commits/31f46d666c7938b308ec64617a22ea86d8808066#diff-8f82beb93a8fd8621acdff8f34e0d3d3R16) ,  it would be better written as: Change the UI5 option from `data-sap-ui-frameOptions="trusted"` to `data-sap-ui-frameOptions="allow"`

**Comment by stanleychh** [comment]
Please add [onListItemPress function ](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1/commits/3a0bc0281edb38be2290e6c703af2dce8e30c286#diff-19e1ab480575c8268445e5c1150c0875R14-R18) at [Step 15th](https://developers-qa.sap.com/tutorials/luigi-app-configuration.html#9c766dcd-fdc3-4e25-9a37-8b3bd3e98eb7). Thanks

**Comment by stanleychh** [comment]
@alexandra-simeonova , the above comment is still missing. Please add add [onListItemPress function ](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/1/commits/3a0bc0281edb38be2290e6c703af2dce8e30c286#diff-19e1ab480575c8268445e5c1150c0875R14-R18) at [Step 15th](https://developers-qa.sap.com/tutorials/luigi-app-configuration.html#9c766dcd-fdc3-4e25-9a37-8b3bd3e98eb7). Thanks

**Comment by stanleychh** [comment]
Good job. It looks good to me. Waiting for the final review by @hardl

**Comment by hardl** [comment]
there seems to be an inconsistency wrt locales, i already requested a change at the example app. Locales should use proper tags, as in this code snippet 
So it looks like it was like that initially but then got changed, because in a following snippet it is a language name
[Uploading... image.png ]

**Comment by stanleychh** [comment]
A new [Pull Request](https://github.wdf.sap.corp/staging-for-SAP-samples-public/luigi-micro-frontend-application/pull/3) which fixed:

- Add SAP logo as header logo
- Enrich README.md in UI5 micro frontend
- Change locales to official tags, like `en-US` & `de-DE`
- Improve user experience at product details page (hide error message at beginning)
- Support i18n on micro frontend, both(React & UI5)

**Comment by alexandra-simeonova** [comment]
Added Localization steps in tutorial. Fixed some remaining errors in this PR: https://github.com/SAPDocuments/Tutorials-Contribution/commit/893590a2561157fa14b1b7388309c8e6b547a3de

**Comment by stanleychh** [comment]
Looks good to me. Well done @alexandra-simeonova
