### ISSUE TITLE
Duplicated navigation nodes in Docu

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/luigi#1572]
**Description**

Duplicated node entities for documentation after running `npm install` secod time

**Steps to reproduce**

Run `npm install` then `npm run start`  twice

![Screen Shot 2020-08-18 at 09.50.16.png](https://images.zenhubusercontent.com/5e85ddcb5fc38b158b99e42a/67c84b61-b208-4ba7-840a-8963b53f8b0d)

**Comment by maxmarkus** [comment]
We were not able to reproduce it, altough it appears to happen from time to time on local development only. Closing it because of this weirdness.
