### ISSUE TITLE
Luigi elevator pitch

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#1594]
Create a short elevator pitch video for Luigi.

**Comment by alexandra-simeonova** [comment]
Link on Youtube: https://www.youtube.com/watch?v=ALbnq7LG-Lg

**Comment by UlianaMunich** [comment]
reviewed and shared with @alexandra-simeonova couple of ideas for improvements, other than that amazing job!!!

**Comment by alexandra-simeonova** [comment]
Elevator pitch with improvements from suggestions: https://www.youtube.com/watch?v=RktekHp9SpQ
