### ISSUE TITLE
Modal and splitView closing issue

### ISSUE THREAD

**Issue by parostatkiem** [SAP/luigi#1614]
**Description**
It looks like modal and splitView don't like to be displayed together. 
See [this issue](https://github.com/kyma-project/console/issues/1949) for the details.

**Expected result**
When I close the modal, the modal is closed. Nothing more happens.

**Actual result**
When I close the modal, splitView is either closed too or stays on the page forever (ignores `handler.collapse()`)

**Steps to reproduce**
I can provide you access to one of our test clusters if you want to experience it personally.

**Troubleshooting**

**Comment by JohannesDoberer** [comment]
Issue resolved via phone call.
After create/edit api rule close the modal via luigi client `closeCurrentModal` and do not navigate without reinit the split view.
