### ISSUE TITLE
Pipeline migration

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1642]
from travis-ci.org to travis-ci.com

travis-ci.org will be shut down EOY

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by ndricimrr** [comment]
Take a look at [Migration Guide](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

**Comment by stanleychh** [comment]
Note: 
Based on research, the repository administrator can do this migration by few clicks.
1. Visit [travis-ci.org/account/repositories](travis-ci.org/account/repositories)
2. Click on **Sign up for the beta** button on left menu
![beta.png](https://images.zenhubusercontent.com/5efc5c163b91075e7a417ffc/d3c50ee9-8954-4101-b978-4c291f826cfc)
3. According to [SAP GitHub](https://github.com/SAP) information, I have emailed to [developers@sap.com](developers@sap.com
) and waiting for the administrator's response.

**Comment by stanleychh** [comment]
Updates:

I have contacted with [Michael Picht](michael.picht@sap.com), who is one of the administrator of [SAP GitHub](https://github.com/SAP/), for helping trigger the Travis migration button. However, he had security and data protection concerns and suggested filing a ticket for check. https://github.wdf.sap.corp/OSPO/OSPO-request/issues/476

After we got the approval from the central procurement team, Michael will help this out.

**Comment by stanleychh** [comment]
Updates:

Missing the last step to migrate luigi to .com via https://travis-ci.com/organizations/SAP/migrate
![Screenshot 2020-10-19 at 10.05.59.png](https://images.zenhubusercontent.com/5efc5c163b91075e7a417ffc/4d7f3ea2-019b-4ec9-a3ab-2aa88d547f53)

Michael will back to office on Oct 22nd. We will continue the migation task.

**Comment by stanleychh** [comment]
Luigi on Travis dot com domain: https://travis-ci.com/github/SAP/luigi

**Comment by stanleychh** [comment]
Luigi is running properly on travis-ci.com
Migration completed.
