### ISSUE TITLE
React example install script error

### ISSUE THREAD

**Issue by cuppar** [SAP/luigi#1673]
Hi guys, I used the React example install bash script(react.sh) work well last week, but today I try it again, but I get an error say "Luigi is not defind", and the `luigi-core` floder is not in my `public` floder, could you check it?

the cammand: `bash <(curl -s https://raw.githubusercontent.com/SAP/luigi/master/scripts/setup/react.sh)`

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by GO-gyan** [comment]
@JohannesDoberer When can we expect this issue to be resolved?

**Comment by JohannesDoberer** [comment]
Hello @GO-gyan and @cuppar, 

the script is fixed and already released.
I'm sorry, I have forgotten to "ping" you about the status. 

Best regards,

Johannes
