### ISSUE TITLE
Fix "double shadow" in splitview when modal is active

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1695]
How to reprodcue it.
- Open a splitview and within this splitview open a modal.
- In this modal activate a backdrop and you will get a double shadow in the splitview iframe.

Expected result:
Same shadow as in the above iframe ![Bildschirmfoto 2020-11-09 um 14.26.17.png](https://images.zenhubusercontent.com/5c346c4d86008d0a2e182a83/45b58ce4-69a6-441f-a260-463ef645f8c3)

Most likely it is not a css issue. It has something to do how backdrops are displayed.

**Comment by rafalgamon** [comment]
These are screenshots from windows (but now on Mac is same) and as you can see each screenshots show everythings is ok.

 One of these shows modals open from top of split screens and second from bottom. Here  I shows confirmsModal and normal modal open by `LuigiClient.linkManager().withParams({test: true}).openAsModal('/projects/pr1', {title:'Logs', size:25})`

Before It didnt work on Mac but after remove cash memory and rebuild everything from scratch now it is ok.
![FireShot Capture 004 - Application One - localhost.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/6384ab20-4848-4c82-930a-d490da3869b3)![FireShot Capture 005 - Application One - localhost.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/eb421427-9536-4df3-ab68-d8b2d1ded0fe)![FireShot Capture 006 - Application One - localhost.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/4330114a-0fef-4e02-b3ed-59903c43a56f)![FireShot Capture 007 - Application One - localhost.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/eb85e37c-14bb-41a9-a11d-ae66fdcdefca)
