### ISSUE TITLE
CSS problem in Docs website after Luigi upgrade

### ISSUE THREAD

**Issue by legteodav** [SAP/luigi#1698]
**Description**
After upgrading docs website to luigi 1.4.0.0, we have several css issues. 
If you upgrade to Luigi 1.5.0.0

**Expected result**
After upgrade, Doc website should looks the same as in Prod (using 1.2.0.0 library).

**Actual result**
With luigi 1.4.0.0 several css problems
With luigi 1.5.0.0 several css problems + left menu scrollbar disappears...

**Steps to reproduce**
This style makes scrollbar disappearing from left menu (in Luigi 1.5.0.0, not in 1.4.0.0): 

.lui-fd-side-nav-wrapper {
  scrollbar-width: auto;
  &::-webkit-scrollbar  {
    width: 0;
  }
}

**Comment by hardl** [comment]
should be fixed with latest doc release
