### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by sundarvc** [SAP/luigi#1706]
Hi Luigi team,

I am running the Angular example after creating the dist folder using nginx as my web server.
The app works fine but all the icons are garbled. Any reason why ?

Thanks,
Sundar

**Comment by hardl** [comment]
Hi,
I assume it is because of missing mime-types in your nginx configuration for web fonts.
See https://github.com/kyma-project/console/tree/master/core/nginx for an example configuration.

Best regards

**Comment by hardl** [comment]
Please reopen, if that doesn't solve the problem.

**Comment by GO-gyan** [comment]
Hi Team,

I followed above steps but it didn't solve the **icon issue**. I tried running the default Luigi **react** example by creating the production build and configuring the nginx. It is running fine with development build but not with production build. Please check. 

![image](https://user-images.githubusercontent.com/22589922/101875573-db08c500-3bb0-11eb-9dcc-409739c7a1c5.png)
