### ISSUE TITLE
withoutsync should use history replaceState instead of pushstate

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1719]
... to avoid erroneous browser back behaviour.

**Current Situation** (Assumption, double-check):
* when there is a route change within a micro frontend iframe induced by a location change, a new state is added to the browser history.
* if the micro frontend is now sending a linkmanager.withoutsync.navigate to luigi core, luigi also add a new state to browser history.
* if you click on browser back button now, you end in an inconsistent "half-"state, so you have to press back twice to go to previous state and active node indication is out of sync in between.

**Comment by andrei-scripcaru** [comment]
I can confirm the existence of this (presumably) bug.

Browsers: Safari, Chrome, Firefox.
OS: MacOS.
