### ISSUE TITLE
hideNavigation should hide completely the left nav bar

### ISSUE THREAD

**Issue by ionutcirja** [SAP/luigi#1722]
When hideNavigation settings value is true, if a skipped route is accessed a remaining of the left navigation bar can still be seen like in the attached picture.

<img width="492" alt="Screenshot 2020-11-24 at 13 59 28" src="https://user-images.githubusercontent.com/5065425/100104097-a92bfa80-2e5d-11eb-9da5-20c5470fe827.png">

**Comment by legteodav** [comment]
Hi @ionutcirja ,

I was trying to reproduce the bug in a couple of application, but i couldn't....
Can you tell me in which application and share with me your Luigi config? 

Thanks a lot
Cheers

Davide

**Comment by ionutcirja** [comment]
Hi,

I will update my sample app today and provide you a link.

Many thanks,
Ionut

**Comment by legteodav** [comment]
Hi Ionut,

did you update your sample and shared the link?

Thanks
Cheers

Davide

**Comment by JohannesDoberer** [comment]
Hey @ionutcirja, 
any news on that?

**Comment by JohannesDoberer** [comment]
Due to inactivity I will close this issue.
Feel free to reopen it if the bug still exists.
