### ISSUE TITLE
Docu: bug in the search, locked on 2nd search attempt

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/luigi#1732]
To reproduce:
- go to the [Docu](https://docs.luigi-project.io/docs/)
- search anything and click on the result
- try to search something else and the search is locked, can't type anything

![Screen Shot 2020-11-25 at 14.55.32.png](https://images.zenhubusercontent.com/5e85ddcb5fc38b158b99e42a/593c8292-eff1-405e-a36f-6a905011d489)

**Comment by legteodav** [comment]
Hi @UlianaMunich ,

Doc website Search is still using docSearch.js... 
Using Luigi Global Search and upgrade to Luigi 1.4.0 had not been merged yet to the master branch (still on Feature Branch).
I guess in next release (once we merge feature branch) error will disappear.

Cheers
Davide

**Comment by hardl** [comment]
should be fixed with latest doc release
