### ISSUE TITLE
global search enhancements

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1738]
Add following features
* scroll-into-view for search result items (when doing keybard navigation)
* possibility to define a placeholder text for search field (localizable)
* allow to define listener for "toggleSearch" in search provider, getting visibilityState and inputElement

**Comment by legteodav** [comment]
Actually scroll-into-view for search result items (when doing keyboard navigation) it working when you use "default" result rendered.
If you use customSearchResultRenderer, you need also to implement the keyboard navigation. (this it what was happening in Luigi Doc Application)

**Comment by UlianaMunich** [comment]
Strange double-border in the popover
![Screen Shot 2020-12-01 at 10 55 57](https://user-images.githubusercontent.com/2720077/100726589-6fab4000-33c5-11eb-97dc-783951c43e3b.png)

**Comment by legteodav** [comment]
The ccs problem (border) should have been fixed in the feature branch, here the link of the preview:

https://deploy-preview-1734--confident-mccarthy-73315c.netlify.app/docs/getting-started
