### ISSUE TITLE
[Feedback] Improve onboard experience for newbies.

### ISSUE THREAD

**Issue by robsontenorio** [SAP/luigi#1740]
**Description**

Video tutorials are great for getting high level understanding. But, following docs as a newbie on microfrontend world i got confused about main goal: compose multiple aplications with Luigi. 

**Reasons**

So far I understand i would have a main app (luigi-core) and mutiples apps (luigi-client). I can install and run the Vue example. 

![image](https://user-images.githubusercontent.com/118955/100493119-968e1b80-3112-11eb-8125-fb70d8fb4baf.png)

I was expecting to see an example of two distinct apps codebase (luigi-client) being composed by main luigi-core app. But the provided example gives me a  "all in one". Am I missing something?

![image](https://user-images.githubusercontent.com/118955/100493160-187e4480-3113-11eb-8981-b0e859866206.png)

**Comment by alexandra-simeonova** [comment]
Hello, 

Thank you for checking Luigi out. We want to improve the documentation, so feedback is always appreciated.

The Luigi Client is not really an app itself, but a concept that refers mostly to the [API](https://docs.luigi-project.io/docs/luigi-client-api) and micro frontend options Luigi offers. How you configure the additional apps is up to you. The Vue example you installed is on a more simple "Hello World" level, but it does include some small micro frontends/"apps"/views in the `views` folder, such as `sample1.vue` and `sample2.vue`. If you want to take a look at a more complex example, we recommend this [Luigi tutorial](https://developers.sap.com/group.luigi-app.html) or the [Luigi Fiddle](https://fiddle.luigi-project.io/) as a good place to start. Please let us know if you have questions here or on our [Slack channel](slack.luigi-project.io).

**Comment by alexandra-simeonova** [comment]
Hi @robsontenorio, I will close this issue unless there are further comments because we made the improvements in https://github.com/SAP/luigi/pull/1766
