### ISSUE TITLE
Please, can you provide an example how to add external designed header?

### ISSUE THREAD

**Issue by szai0103** [SAP/luigi#1741]
I didn`t find any proper way how to use our own company UI components instead Fiory designed ones. In this regard, I would want to ask if you have an existing example to show how it works?

Thanks in advance.

**Comment by JohannesDoberer** [comment]
Hello,
we are know this issue and working on it #1598.
Maybe as a workaround you can take a look on the [FAQ](https://docs.luigi-project.io/docs/faq) _I don't want to use the default Fiori Fundamentals style. How can I style Luigi differently? How can I change the look of Luigi's UI?_

Best regards

**Comment by JohannesDoberer** [comment]
Feel free to reopen, if you need more information.
