### ISSUE TITLE
Split View Example

### ISSUE THREAD

**Issue by szai0103** [SAP/luigi#1764]
Hi, all, sorry if someone has already asked for this but I couldn`t find any example with this. I really want to take advantage of splitView for displaying multiple micro frontends into another, but need some working example to see how to configure it. Can you provide one, please?

**Comment by alexandra-simeonova** [comment]
Hello 🙂 

as we discussed per e-mail, currently an example can be found in our e2e test application, e.g. https://github.com/SAP/luigi/blob/master/test/e2e-test-application/src/app/project/project.component.ts#L213

The instructions on how to install and run this example are here: https://github.com/SAP/luigi/tree/master/test/e2e-test-application#luigi-sample-and-e2e-test-application-written-in-angular

More information on splitView can also be found on https://docs.luigi-project.io/docs/luigi-client-api?section=splitview.
