### ISSUE TITLE
Custom usersettings micro frontends

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1770]
Next to our simple settings ui based on the schema, a micro frontend provider should be able to add his custom user setting views to the settings dialog.
One usecase example would be theming, see ![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/06ec92e5-d125-47e3-972c-2732b50ee6b3)

**Comment by JohannesDoberer** [comment]
- Introduce a LuigiUserSettingsClient within LuigiClient (like LuigiElements)

LuigiUserSettingsClient
  -> read and write the user settings object which life in the dialog
