### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by GO-gyan** [SAP/luigi#1776]
**Description**
This issue is related to the closed issue [https://github.com/SAP/luigi/issues/1706](https://github.com/SAP/luigi/issues/1706).
I followed above steps given as a solution to [https://github.com/SAP/luigi/issues/1706](https://github.com/SAP/luigi/issues/1706) but it didn't solve the icon issue. I tried running the default Luigi **react** example by creating the production build and configuring the _nginx_. It is running fine with development build but not with production build. Please check the problem.

All the ICONs are distorted.

**Expected result**
Icon should be appear as expected.

**Actual result**
![image](https://user-images.githubusercontent.com/22589922/101875573-db08c500-3bb0-11eb-9dcc-409739c7a1c5.png)

**Steps to reproduce**

**Troubleshooting**

**Comment by GO-gyan** [comment]
Hi,

I added <meta charset="UTF-8" /> to the head of my index.html file and it is started working.

**Comment by stanleychh** [comment]
I was not able to reproduce this issue. Icons were displayed properly.
