### ISSUE TITLE
Apply guidelines for user settings dialog

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1777]
Please find Desktop and Phone Specification on this page
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104434679

**Comment by UlianaMunich** [comment]
to test the dark theme please add to the Header next line:
<link rel="stylesheet" href="https://unpkg.com/@sap-theming/theming-base-content/content/Base/baseLib/sap_fiori_3_dark/css_variables.css">
