### ISSUE TITLE
Views not preserved when navigating to/from a viewGroup

### ISSUE THREAD

**Issue by alrenik** [SAP/luigi#1804]
Hello team Luigi!

I have defined the viewGroup field for my nodes but iframes are not being reused nonetheless. Is there anything else that needs to be done for this feature to work?
There is an if-condition on a field named 'viewgroup' at [core/src/App.html#L293](https://github.com/SAP/luigi/blob/ab58877aedb936e75e00e5b51494c2451b0b0bf3/core/src/App.html#L293) but this field doesn't seem to be assigned anything anywhere... Maybe it's a bug?

And a side question; Is it possible to access "preservedView"s using the Luigi.navigation().navigate method and NOT the back button/method?

**Comment by legteodav** [comment]
Hi @alrenik,

I was checking and it is working... Probably, you missed some configuration and we should improve our documentation.

I created an example in our test e2e-application in this branch: https://github.com/legteodav/luigi/tree/1804_views-not-preserved

1)go to directory https://github.com/legteodav/luigi/tree/1804_views-not-preserved/test/e2e-test-application
2)npm start
3)Open url: http://localhost:4200/view-groups/1

You might notices that VG1 and VG2 are in the same viewgroup. I also added more info in the component, so you can check ID of the iframe (if it is changing or not) and timestamp of the component (plus some info about iframes in the page and Luigi config).

I guess you are probably missing the mandatory configuration:

`  preloadViewGroups = true,
  viewGroupSettings = {
    view_group_components: {
      preloadUrl: '/sampleapp.html#/view-group/preload'
    }
  };`

Every time you create a viewgroup set, you need to:
- set preloadViewGroups: true
- define a preload url for your viewgroup id (in the previous example)

Once you define the preload, Luigi will create an iframe at startup and it will be used to load all your micro frontends with the same viewgroup. 

Let me know if it was clear or you still have some doubts

**Comment by legteodav** [comment]
Hi @alrenik,

If you refer to:

const preservedViews = this.getPreservedViewsInDom(iframesInDom);

in theory you can have the same result with this js line:

`document.querySelectorAll('.iframeContainer iframe').filter(iframe => iframe.pv)`

I can talk with my colleagues, but i don't think it is a good idea expose this variable in Core API.

Cheers
Davide

**Comment by alrenik** [comment]
Thank you @legteodav. Your example was helpful; there was an error in Luigi's docs.
And about the answer you gave to my side question; I'm getting my expected behavior with the now working reusable iframes. :+1:
