### ISSUE TITLE
OIDC Implicit flow (id_token) + fragment gets in infinite loop

### ISSUE THREAD

**Issue by valentinvieriu** [SAP/luigi#1825]
**Description**

OIDC Implicit flow (id_token) + response as fragment it is a common flow in SPA applications.

**Expected result**

OIDC Implicit Flow should work

**Actual result**

Application gets in an infinite loop

**Steps to reproduce**

Use https://fiddle.luigi-project.io/ and configure the auth section like below:

```
        auth: {
            use: 'myOpenimyOIDC',
            myOpenimyOIDC: {
                idpProvider: window.LuigiAuthOIDC,
                authority: 'https://apskyxzcl.accounts400.ondemand.com',
                logoutUrl: '/auth/idpmock/logout.html',
                scope: 'openid',
                redirect_uri:"https://fiddle.luigi-project.io/",
                post_logout_redirect_uri: '/auth/logout.html',
                client_id: 'd0316c58-b0fe-45cd-9960-0fea0708355a',
                response_type: "id_token", // for PKCE
                response_mode: "fragment", // change between `query` and `fragment`
                automaticSilentRenew: false,
                accessTokenExpiringNotificationTime: 60,
            }
        },
```

You will end up in a redirection loop.
**Troubleshooting**

**Comment by JohannesDoberer** [comment]
Hey Valentin, which storage type are you using for storage the token? 'Localstorage', 'sessionstorage' or 'none'?

**Comment by valentinvieriu** [comment]
As you see in the sample above, I don't set it. I guess is the default one. 
PM me if you cannot access that IDP provider or feel free to use any other IDP provider, the situation is the same
