### ISSUE TITLE
Search/Filter for usersettings dialog

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1834]
TBD

**Comment by JohannesDoberer** [comment]
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104434679
Search can be configurable like display or not.

**Comment by UlianaMunich** [comment]
Here are the visuals from Fiori 3:
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2060056990
