### ISSUE TITLE
Add list group header to the left nav of user settings dialog

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1837]
Add a new category on left nav for user settings.
Also the schema needs to be extended.

For more details (B5)
https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2104434679
https://wiki.wdf.sap.corp/wiki/display/visualcore/Settings+%28Fiori+3%29+-+Master+Area
"Current App" and "General settings" should also be configurable

**Comment by hardl** [comment]
In the first link, there is no B5, second link is dead.
Still valid?
