### ISSUE TITLE
Setting for width of the nav bar doesn't seem to work

### ISSUE THREAD

**Issue by uxkjaer** [SAP/luigi#1860]
**Description**
I've added the css for the nav bar to set a custom width, but it doesn't have any effect. My nav bar is still 15rem
![image](https://user-images.githubusercontent.com/8186370/106607165-bb898980-65ae-11eb-954f-0cb24758597f.png)

**Comment by hardl** [comment]
Hi, which version of luigi are you using?

**Comment by hardl** [comment]
Anyway, i guess you have to put your <style> AFTER luigi.css <link> in order to override the variable.

**Comment by uxkjaer** [comment]
An upgrade and move after the css import helped. Rookie mistake.

Thanks!
