### ISSUE TITLE
New to Luigi - need an example

### ISSUE THREAD

**Issue by sundarvc** [SAP/luigi#1862]
Hi Team,

I am learning Luigi and I have a need to develop a JS based front-end app for my project.
I did watch the videos and tutorials but they seem kind of basic . I would like an advanced version in plain JS (if possible) that shows how to use the Luigi client and core libraries and integrated with the other UI controls. Can you please notify when such an example is available ? I am hoping soon , as many have requested for the same.

Thanks,
Sundar

**Comment by JohannesDoberer** [comment]
Hello,
welcome to Luigi :).

Here is a link to our [tutorial](https://developers.sap.com/group.luigi-app.html)
In addition on our [getting-started](https://docs.luigi-project.io/docs/getting-started) page we provide a few hello world examples written in different frameworks.

Cheers

**Comment by sundarvc** [comment]
Thanks. Do you have one that uses just plain JS with some Luigi calls ?
I am getting a "Luigi is undefined error" when I call the API from my JS
app.

**Comment by hardl** [comment]
Have a look at https://docs.luigi-project.io/docs/getting-started/?section=examples, first section "HTML file". It uses a cdn version of luigi library but serves as a good starting point for a luigi core app in vanilla js.

For a vanilla js micro frontend, maybe our fiddle example could be a good source for inspiration https://github.com/SAP/luigi/blob/master/website/fiddle/public/examples/microfrontends/multipurpose.html

**Comment by JohannesDoberer** [comment]
I would close this issue. I hope you get a good starting point for further implementations with Luigi.
If you have any issues regarding this topic feel free to reopen the ticket.

Cheers
