### ISSUE TITLE
Luigi Micro Frontend Container Component

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1864]
A component (web component) that can be included in an arbitrary application rendering a luigi micro frontend (iframe or web component based) without the need of being a luigi core application.

**Comment by ndricimrr** [comment]
Future steps:
- Travis Setup for experimenting/testing with it
- Published via nightly on commit message like the cra-template
- give package different name, and rc version number

Topics to further discuss

- Discuss common functionality and how to share it to avoid duplication. (possible switch to TS)
- Discuss Communication Interface for the Container

**Comment by hardl** [comment]
current development branch: https://github.com/SAP/luigi/tree/luigi-container
