### ISSUE TITLE
Support multiple OIDC clients in auth config 

### ISSUE THREAD

**Issue by favetelinguis** [SAP/luigi#1867]
We use federated user access from five oidc providers. However, given the examples of luigi it looks like you can only configure one client?

Please clarify how to use multiple clients if possible.

**Comment by JohannesDoberer** [comment]
Hello,
yes, that is true. Luigi don't support to configure multiple OIDC clients.
For this scenario you need your own solution.
An example how to deal with multiple OIDC clients could be [dex](https://github.com/dexidp/dex) or something similar.

**Comment by JohannesDoberer** [comment]
I hope the recommendation helps you to find a solution.
I would close this issue.
If there are further questions feel free to reopen.

Cheers
