### ISSUE TITLE
Shellbar user initials when there is no avatar

### ISSUE THREAD

**Issue by UlianaMunich** [SAP/luigi#1868]
FD Styles guidelines https://sap.github.io/fundamental-styles/?path=/docs/components-shellbar--primary

"The primary shellbar displays a logo, title, and an avatar where the user settings are found. If the avatar does not contain a thumbnail, then the initials of the user will be displayed."

Corner cases: 
- If the user has more than 2 names/surnamees show only first 2 initials
- if the user doesn't have a Name and Surname what to show then?

**But important to leave the option to use a "user icon" as we have now  to not break the external customers' apps.**

**Comment by hardl** [comment]
implemented here: https://github.com/SAP/luigi/pull/2074
