### ISSUE TITLE
Global side nav follow up

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1932]
- Missing parts
-> docu and tests. (Since it is an experimental feature, official documentation is not necessary here)

- Improvements
-> color of active/hover list entries in global nav especially on different themes:
```
https://unpkg.com/@sap-theming/theming-base-content@11.1.27/content/Base/baseLib/sap_fiori_3_dark/css_variables.css
https://unpkg.com/@sap-theming/theming-base-content@11.1.27/content/Base/baseLib/sap_fiori_3_hcb/css_variables.css
```
-> to much spacing between bottom and 'bottom' list entries
Have a look [there](https://sap.github.io/fundamental-styles/?path=/docs/components-side-navigation--cozy)

- Bugs

1. Navigate between home page and a micro-frontend view with tab nav. There is a JS console error. 
![js-error.png](https://images.zenhubusercontent.com/5efc5c163b91075e7a417ffc/276ed46b-4e8e-42ae-b1cb-7f576f5ddb2d)
2. if hideSideNav is set to true on a global node, iframe container has left 0 instead of global nav width
![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/3e3701cf-7875-4409-a5f7-6a557b282e1f)

**Comment by hardl** [comment]
added a bug, see updated description

**Comment by JohannesDoberer** [comment]
When I click on `hide Side Navigation` in our e2e test app the tab nav is overlapping the global nav (on every viewport).
![Bildschirmfoto 2021-03-24 um 11 53 20](https://user-images.githubusercontent.com/14272184/112299090-bfc15180-8c97-11eb-9452-f63f26472235.png)

**Comment by stanleychh** [comment]
@JohannesDoberer good catch! Pushed the fix.
