### ISSUE TITLE
fix dependency alerts

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1948]
https://github.com/SAP/luigi/security/dependabot

**Comment by stanleychh** [comment]
Noted down those alerts by path

1.  `/core/examples/luigi-example-angular`
is-svg, ssri, glob-parent, normalize-url, webpack-subresource-integrity, ini, postcss

2. `/core/examples/luigi-example-vue`
trim-newlines, normalize-url, glob-parent

3. `/website/docs`
glob-parent, trim, highlight.js, trim-newlines, normalize-url,


4. `/website/landingpage/dev/`
is-svg, serialize-javascript, normalize-url, trim-newlines, glob-parent, postcss, ws

5. `/scripts/`
highlight.js, normalize-url, glob-parent, trim

6. `/core/`
normalize-url, trim-newlines, glob-parent

7. `/client/` 
 glob-parent


8.  root Luigi
y18n, ini, trim, yargs-parser, normalize-url, trim-newlines, glob-parent, ssri,

**Comment by stanleychh** [comment]
Note: Also try to use [depcheck](https://www.npmjs.com/package/depcheck) finding out unused dependencies.

**Comment by UlianaMunich** [comment]
taking /core/examples/luigi-example-vue

**Comment by UlianaMunich** [comment]
PR for AngularJS example: https://github.com/SAP/luigi/pull/2128
