### ISSUE TITLE
Create Luigi onboarding guide

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#1983]
Create an onboarding guide which introduces new developers to Luigi. It should include:
- introduction to Luigi 
- how to set up your computer for development
- internal processes
- guidelines for writing code/content 
- any other useful tips/links

**Comment by alexandra-simeonova** [comment]
Luigi onboarding guide link: https://github.tools.sap/luigi-project/documentation/blob/master/onboarding.md

**Comment by ndricimrr** [comment]
Looks pretty good 👍 

One small note, maybe replace the `lerna boostrap` with `lerna bootstrap --force-local` , That's what we [use usually ](https://github.com/ndricimrr/luigi/blob/master/test/e2e-test-application/README.md)to avoid some dependency not linking.

**Comment by alexandra-simeonova** [comment]
Thank you, I updated it to `lerna bootstrap --force-local`. Btw, I copied the content from here: https://cxwiki.sap.com/display/luigi/Setup+for+new+team+members, so I will also change it in the wiki. Thank you for the review. 👍

**Comment by alexandra-simeonova** [comment]
The issue is closed, but we can continue adding content as needed (more details can be revealed once the new employees actually join).
