### ISSUE TITLE
`Luigi.ux().setDocumentTitle` not updating document.title

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [SAP/luigi#2001]
**Description**

When document title is initially an empty string then setting title programicaly have no effect.

**Expected result**

Document title should be changed.

**Actual result**

Document title is not updated.

**Steps to reproduce**

Luigi Config:
```typescript
Luigi.setConfig({
  settings: {
    header: {
      title: '',
      altText: 'Brand name',
      logo: '/assets/images/logo.svg',
      favicon: '/assets/images/favicon.svg',
    }
  }
});
```

After application is loaded run `Luigi.ux().setDocumentTitle('xyz');` in console.

**Troubleshooting**

Found that title is not updating when header title is empty string.

**Comment by stanleychh** [comment]
Note: This bug happens when no title was set at beginning only. `setDocumentTitle` function works fine when title is not empty.
