### ISSUE TITLE
misconfiguration in default fiddle example

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2117]
In the current fiddle default, validWebcomponentsUrls is configured under settings->navigation. This is wrong and must be moved up under navigation directly.

![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/0aa6fd57-0ce8-45e2-84bd-2425b0e91b49)

**Comment by RhnSharma** [comment]
I would like to take this one.
