### ISSUE TITLE
reduce bundle-size

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2134]
investigate if and how the bundle size of luigi.js and .css can be reduced.

Not in scope: IE11 bundles.

starting point:

```
PASS  ./public/luigi.js: 568.73KB < maxSize 600KB (no compression) 

 PASS  ./public/luigi.css: 573.21KB < maxSize 600KB (no compression) 

 PASS  ./public-ie11/luigi-ie11.js: 781.5KB < maxSize 799KB (no compression) 

 PASS  ./public-ie11/luigi-ie11.css: 573.69KB < maxSize 600KB (no compression) 
```

**Comment by JohannesDoberer** [comment]
message obj for init and specialIframes in App.html and context update in iframe.js could be in one function.. it's the same code

**Comment by JohannesDoberer** [comment]
we have to functions *replaceVars* in genericHelpers and iframeHelpers.. maybe they do the same
