### ISSUE TITLE
Error Handling on Micro Frontend Level

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2148]
Luigi should provide an error handler mechanism on core level which can be used to implement a central error handler within the core app. The error handler receives all unhandled errors of the micro frontends, which are using the Luigi Client.
The Luigi Client should wrap window.onerror handler and propagate the error to the host frame

**Comment by JohannesDoberer** [comment]
on node level it should be a property `onRuntimeErrorHandler` from type object.
```
onRuntimeErrorHandler: {
   errorFn: (error)=>{

   }
}
```

It should be possible to disable the `luigi runtime error handler` on mf side.
Add attribute `disable-luigi-runtime-error-handling` to window.document.head.
