### ISSUE TITLE
splitview bottom not adjusting to fiddle footer

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2150]
![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/931c805d-d9be-48a9-9184-c104d4ed76b7)

**Comment by rafalgamon** [comment]
I check it on each browser (edge, chrome, firefox, safari) and everything is fine. I'm adding screen shoots in attaches. ![Zrzut ekranu 2021-07-16 o 10.43.45.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/4f02298a-9f07-4ba5-964a-4c069dff731d)![Zrzut ekranu 2021-07-16 o 10.43.02.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/33c19815-286d-4bba-98ca-781c080e7387)![Zrzut ekranu 2021-07-16 o 10.42.35.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/ae0288d4-d6e2-4f45-9b86-46a919d31884)![Zrzut ekranu 2021-07-16 o 10.41.52.png](https://images.zenhubusercontent.com/60c33850f9be74b7c84d74bf/6c6faf84-3cdc-4d29-a7f6-b0938d09ab08)

**Comment by hardl** [comment]
I can't see splitview opened in your screenshots...
Since we show a footer in fiddle, there are overrides for the bottom prop of nav and content 
```
.show-bar #app .fd-app__sidebar, .show-bar .fd-page.iframeContainer {
    bottom: 50px !important;
}
```
but it is missing for splitViewContainer.
![image](https://user-images.githubusercontent.com/7690363/125941142-3a268972-4cdd-4112-925f-f79d7e27536d.png)

Fix is to add it to the above selectors so it looks sth like:
```
.show-bar #app .fd-app__sidebar, .show-bar .fd-page.iframeContainer, .show-bar #app .splitViewContainer {
    bottom: 50px !important;
}
```
