### ISSUE TITLE
core api for query params

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2176]
US: 
As a luigi core developer, i want to have a convenient api to access query parameters from the current url and use it e.g. for viewUrl templating.

AC:
- [ ] new `routing` "sub-api" added to Luigi core API with functions to get and set query params.
- [ ] manipulating/setting query params must not reload the page, i.e. must be done via history pushState.
- [ ] transparent param resolution depending on routing strategy (hash or path), i.e. if hashRouting===true, pseudo query params (after hash) should be used (https://domain/bla/#/route/to/node?x=y), otherwise `window.location.search`.
- [ ] `Luigi.routing().getQueryParams()` function available for node templating, i.e. it must be possible to define a viewUrl like `viewUrl: './path/to/mfe/?x={routing.queryParams.x}'` (see i18n section here https://docs.luigi-project.io/docs/navigation-advanced/?section=dynamic-viewurl-parameters)
- [ ] URLSearchParams API (https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is used for all operations, no custom string parsing or regex (except for extracting pseudo query part from hash)

**Comment by JohannesDoberer** [comment]
Follow up ticket #2216
