### ISSUE TITLE
modal spinner container misplaced

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2194]
![image.png](https://images.zenhubusercontent.com/5b8418bc79c9991fcdb9a678/6950e365-f97f-4a13-9391-30b5edf170c3)

add a selector to set "left" to 0 for spinnerContainer in modal,
e.g.
```
#app .lui-modal-mf .spinnerContainer {
    left: 0;
}
```

**Comment by Patil2099** [comment]
I would love to take this up
