### ISSUE TITLE
expose getCurrentLocale in webcomponent luigi client

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2217]
steps to do:

- [ ] add it here https://github.com/SAP/luigi/blob/546cf9f4a8e907ae4606a09f90dde06f649f125f/core/src/services/web-components.js#L36, like `getCurrentLocale: window.Luigi.i18n().getCurrentLocale`

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue!

**Comment by pran01** [comment]
can I work on this?
