### ISSUE TITLE
Remove GA from landing page

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2261]
Will be replaced in the future by a different solution

**Comment by UlianaMunich** [comment]
I don't find this code snippet in our repo but it is live at https://luigi-project.io/: 
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-98366748-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-98366748-4');
</script>`

Is it added on the server side? Or should it be removed from Google Analytics Admin?
