### ISSUE TITLE
Allow HTML in sideNavFooterText OR make it a function

### ISSUE THREAD

**Issue by Wawrzyn321** [SAP/luigi#2321]
**Description**

Currently it's only possible to set `sideNavFooterText` to plain text. I'd like to add more elements here, for example links with `a` element.

We could either allow setting HTML here, or make `sideNavFooterText` accept either string or function - in latter case, the function would be called with each navigation refresh.

**Reasons**

As a workaround, I can use `document.querySelector('.fd-side-nav')` and insert a child below the left navigation, but it will disappear after any navigation change.

**Comment by UlianaMunich** [comment]
Hello @Wawrzyn321, the fix will be released with the next version of Luigi, most likely v1.21.0. Hope it will suit your goal.
