### ISSUE TITLE
Navigation config properties not changeable

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2338]
Please check all navigation config properties if there are changeable.
For more infos see #2319, it's similar.

**Comment by JohannesDoberer** [comment]
Comment from Uliana:
I tested a lot of attributes, all look good, except of 
```
 navigation: {
    validWebcomponentUrls:['https\:\/\/YOURPROJECT\.gitlab\.io\/.?']
  }
```

looks like it is not getting an update on the flight. Need to dig in after the vacation

**Comment by UlianaMunich** [comment]
All is good except of h `validWebcomponentUrls`, created a follow up  [bug report](https://github.com/SAP/luigi/issues/2368)
