### ISSUE TITLE
Navigation flyout styles should use CSS variables

### ISSUE THREAD

**Issue by Wawrzyn321** [SAP/luigi#2356]
**Description**

I want to use themes in my Luigi application. To switch theme, I can just replace the CSS variables stylesheet, and the changes should be picked up automatically.

**Expected result**

All Luigi components use CSS variables.

**Actual result**

I switched theme to dark:
![image](https://user-images.githubusercontent.com/10504661/139856835-d2d89714-946d-440c-982a-d08214293537.png)

As far as I can see in `core/src/navigation/LeftNav.html`, for _background_ a plain color is used, instead of a variable.
![image](https://user-images.githubusercontent.com/10504661/139857090-c4fbfa4b-fbf6-432f-8439-b727085c9dfe.png)

**Comment by Sawthis** [comment]
@UlianaMunich could you create a release with this fix?

**Comment by hardl** [comment]
@Sawthis We will do a new release next week latest.
In the meantime you could use our latest nightly release if you want to try it out, e.g. https://www.npmjs.com/package/@luigi-project/core/v/1.18.2-dev.202111181630
