### ISSUE TITLE
Improve OAuth2 documentation

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#2373]
**Description**

The documentation at https://docs.luigi-project.io/docs/auth-oauth2 should be improved.
- Specify the port does not have to be `4200` 
- Make it more generic instead of specific to Angular example

**Reasons**

For more details, see https://luigi-project.slack.com/archives/CMV4EME3G/p1636635799010200

**Attachments**

**Comment by ndricimrr** [comment]
For the specific scenario mentioned. Can suggest a simple solution with a simple copy script, without including extra config files:

...
The callback.html needs to be copied to a folder in your Luigi Core installation, which is the return path for the IdP provider, configured through the redirect_uri setting. The default location of redirect_uri is /assets/auth-oauth2/callback.html.

//Line added
> For angular based applications the `callback.html` file can be copied using [copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin). Include the following in your webpack configuration file. 

```
const CopyWebpackPlugin = require('copy-webpack-plugin');

{
  plugins: [
    new CopyWebpackPlugin([{
      from: 'node_modules/@luigi-project/plugin-auth-oauth2/callback.html',
      to: 'src/assets/auth-oauth2'
    }])
  ]
}
```


For more simple scenarios such as Luigi setup without a framework you can use any copy plugin to copy the _callback.html_ file. An example is given below using [copyfiles](https://www.npmjs.com/package/copyfiles):

```
"buildConfig": "webpack --entry ./src/luigi-config/luigi-config.es6.js --output-path ./public/assets --output-filename luigi-config.js --mode production",
"build": "npm run buildConfig && npm run copyCallbackOAuth",
"copyCallbackOAuth": "copyfiles -f node_modules/@luigi-project/plugin-auth-oauth2/callback.html public/assets/auth-oauth2"
```

Running `npm run build` should then suffice to bundle the config and also copy the callback file.
