### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by platon-rov** [SAP/luigi#2389]
**Description**

`@luigi-project/client-support-angular` has

```
"peerDependencies": {
    "@angular/common": "^11.0.0",
    "@angular/core": "^11.0.0",
    "@luigi-project/client": "^1.5.0"
  },
```

So when i'm trying to update to Angular 13 I get

```
Package "@luigi-project/client-support-angular" has an incompatible peer dependency to "@angular/common" (requires "^11.0.0" (extended), would install "13.0.2").
```

So I'm concerned about how is it safe to process update.

**Reasons**

New Angular release.

**Comment by JohannesDoberer** [comment]
check if you can define a range like from 11-13
