### ISSUE TITLE
Navigation flyout styles should use CSS variables

### ISSUE THREAD

**Issue by Sawthis** [SAP/luigi#2405]
**Description**

Follow-up issues for : https://github.com/SAP/luigi/issues/2356 . There are still white shadow and white rows separators in dark theme.

**Expected result**

No white shadow and rows separators.

**Actual result**

We have white shadow and rows separators in dark theme.

**Steps to reproduce**

**Troubleshooting**

![Screenshot 2021-11-29 at 12 15 26](https://user-images.githubusercontent.com/74361703/143858881-7047b595-26f8-4f12-912b-310517fcdef8.png)

**Comment by mrCherry97** [comment]
@JohannesDoberer it's resolved? Can I get some updates with it?

**Comment by JohannesDoberer** [comment]
Hey @mrCherry97,
it's available in the new release v1.20.1 which is out since Friday.

Cheers,

Johannes
