### ISSUE TITLE
Add option to not set sandbox attribute on iframe for testing with cypress

### ISSUE THREAD

**Issue by migg24** [SAP/luigi#2434]
**Description**
We are running a luigi application and an app inside it in an iframe created by luigi. Luigi framework automatically adds `sandbox` attribute with some default allow settings and as a user I could add some more. But what I cannot do is remove the `sandbox` completely.

When we try to run a cypress test against the application inside the iframe we get this error:
```
Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.
```

We would like to be able to configure luigi with some kind of "bypassSecurityDisableIframeSandbox" option for the test run. Just to make it clear that its probably not a good idea to do that in production.

If you see any other way of getting this to work any help is appreciated. Currently removing the sandbox attribute looks like the only option for us.

**Reasons**
To make applications inside a luigi iframe testable with cypress.

**Attachments**
Similar issue: https://github.com/cypress-io/cypress/issues/16262

**Comment by hardl** [comment]
One possible option would be to use the **iframeCreationInterceptor** (https://docs.luigi-project.io/docs/general-settings/?section=general-parameters).
There you have the iframe element before it gets added to the DOM, so you could completely remove the sandbx attribute from it.

**Comment by migg24** [comment]
Oh nice, will try this, thanks a lot.

**Comment by migg24** [comment]
It works, thanks for the hint!
