### ISSUE TITLE
Alternative for oidc-client

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2446]
In our current implementation we are using _oidc-client_ v1.11.5. This project is not longer maintained.
Follow-up project is https://github.com/authts/oidc-client-ts

Keep the old oidc-client library in _/plugins/auth/src/auth-oidc/index.js_ that we also can support the implicit flow.
It should be possible that the user can choose which plugin/library he want's to use.

**Comment by JohannesDoberer** [comment]
Imlicit flow was removed with [v2.0.0](https://github.com/authts/oidc-client-ts/releases/tag/v2.0.0)
