### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2497]
TBD
Most of our dependencies are not up to date.

How do we update all these deps?
- lerna
- angular in e2e-app
...

How can we ensure to be up to date with our deps.?

**Comment by stanleychh** [comment]
[npm-check-updates](https://www.npmjs.com/package/npm-check-updates) might help. Further investigation is needed.

**Comment by ndricimrr** [comment]
Epic seems outdated. Duplicate Epic in #2587 already exists
