### ISSUE TITLE
Troubles with using storageManager

### ISSUE THREAD

**Issue by ReflectionGolden** [SAP/luigi#2519]
I'm trying to use storageManager to share data between 2 separately running applications, but the automatically added prefixes added to the storage keys before sending to local storage stop this from working.

Is there a way to stop the Core from adding the prefixes, or is sharing data between separately running client apps not supposed to be a feature as the documentation suggests?

**Comment by alexandra-simeonova** [comment]
Hi ReflectionGolden,
It's not possible to share data between different applications unless come from the same origin, i.e. comply with the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). We will work to fix this in the documentation. Thank you for raising the issue.
