### ISSUE TITLE
Question about storageManager Limitations

### ISSUE THREAD

**Issue by ReflectionGolden** [SAP/luigi#2564]
I've been thinking about the response to my question [here](https://github.com/SAP/luigi/issues/2519), and I'm now asking for some clarification on something.

I would have thought that since Luigi is intended for combining separately developed apps into one space a user can access, wouldn't it be important to include a way to easily share data between different LuigiClient apps which are being developed separately by unrelated teams? Which is why I assumed that storageManager should be capable of that.

It seems very limiting in the way of having applications which are being developed independently of each other but which may want to share data being unable to access local storage data managed by storageManager which comes from the other application.

I at least somewhat expected there to be some way to decide if a piece of data was to be accessible by other apps or only by the app sending the data. What is the reason behind requiring an additional form of local storage manager separate from Luigi to do something like this?

**Comment by JohannesDoberer** [comment]
Hey @ReflectionGolden,
I'll close this issue. If there are more questions feel free to reopen this issue.
Best regards,

Johannes
