### ISSUE TITLE
Provide option to set modal size more precise

### ISSUE THREAD

**Issue by MalteBellmann** [SAP/luigi#2593]
**Description**

Currently, a MFE only has the option to set the modal size as `s`, `m`, or `l`. It would be good if it was also possible to set the width and height in px, rem or % etc.

**Reasons**

**Attachments**

https://github.com/SAP/luigi/blob/ebdfe93018db4d6609f06d45338b242a2dd7672b/core/src/Modal.svelte#L115

**Comment by JohannesDoberer** [comment]
Introduce `width` and `height` and sanitize the values
