### ISSUE TITLE
Bug: LuigiClient doesn't export updateModalSettings

### ISSUE THREAD

**Issue by akatyabg** [SAP/luigi#2606]
The type definition of the `LinkManager` doesn't provide the method `updateModalSettings`: https://github.com/SAP/luigi/blob/master/client/luigi-client.d.ts#L236

The method was introduced in https://github.com/SAP/luigi/issues/2307

**Comment by MichaelBaySAP** [comment]
updateModalSettings is not working yet when I pull the library

**Comment by hardl** [comment]
@MichaelBaySAP the type definition is not yet part of a release.
For now you have two options: 
1) use the nightly build of luigi client (1.20.2-dev.202203142200)
2) bypass typing by using sth. like 
```
(linkManager() as any).updateModalSettings(...)
```

**Comment by MichaelBaySAP** [comment]
Hi Philipp, I have tried to use it like this. However, it is not correctly recognizing Luigi Client. It would be great if you could let me know when the new luigiClient is published in a new release.

**Comment by MichaelBaySAP** [comment]
Hi Philipp,

I have tried it like this but it is not correctly recognizing LuigiClient. It would be great if you could let me know when you publish a new release with the feature. 

Possibly, it is wrong to redeclare the class LuigiClient. However, luigiClient is not known.
![image](https://user-images.githubusercontent.com/40032066/158377734-265b91f0-39b8-4244-8622-55d2960ad7cd.png)
![image](https://user-images.githubusercontent.com/40032066/158377825-8665f759-47d2-4808-8600-3b3c1c922766.png)
![image](https://user-images.githubusercontent.com/40032066/158377886-12c86005-5b19-40f6-9afb-63a7df40cb06.png)

**Comment by hardl** [comment]
Hi @MichaelBaySAP,
just import linkManager directly instead of your LuigiClient wrapper:
`import { linkManager } from '@luigi-project/client';`

**Comment by MichaelBaySAP** [comment]
Thank you it works
