### ISSUE TITLE
shortcut click support for opening node in new tab

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2623]
We have the option to show hrefs for navigation node elements (https://docs.luigi-project.io/docs/navigation-parameters-reference/?section=addnavhrefs). With that, one can use right click and select "open in new tab". But what doesn't work is the OS-specific CTRL+click (windows) / CMD+click (mac), probably because the click handler always does a preventDefault.

Solution:
click event handler should check for ctrl&meta key and if pressed, not call preventDefault

**Comment by dbadura** [comment]
I would also add support for mouse wheel click if it differs somehow in implementation from CTRL+click.

**Comment by hardl** [comment]
> I would also add support for mouse wheel click if it differs somehow in implementation from CTRL+click.

At least on windows chrome/FF/Edge this already works, seems like wheel-click is handled differently
