### ISSUE TITLE
Source maps of core do not reflect lines positions in debugging

### ISSUE THREAD

**Issue by wdoberschuetz** [SAP/luigi#2628]
**Description**
Try to set a breakpoint when debugging i.e. _routing.js_ of the _core_ part of Luigi.

**Expected result**
I'm able to set breakpoints in the code of the core and it reflects the position in the code.

**Actual result**
I.e. I see a line in the code but I cannot set any breakpoint there. When I invoke the method, it seems that the breakpoints are set a few lines up or down the code. It seems that what I see isn't reflected in the sourcemap. 

**Steps to reproduce**
Go to some method in any of the core files, I went to routing.js and tried to set breakpoints in updateModalPathData.

**Comment by hardl** [comment]
let's see if this will be fixed after switching to vite, closing it for now
