### ISSUE TITLE
Trouble with using Certificate with React setup

### ISSUE THREAD

**Issue by ReflectionGolden** [SAP/luigi#2631]
Hi, I'm having problems adding an SSL Certificate to my Luigi Core app due to the setup for react causing the scripts section of the package.json to use the .js files in the src/scripts folder instead of using react-scripts which means I can't use the environment variables I have used for previous react projects.

When I have tried to change towards using react-scripts it hasn't fully started, leaving a blank tab with nothing loading, and I haven't found anything official on this issue.

Has there been anything on this in the past? Such as a way to make it so a core app can run properly using react-scripts?

**Comment by stanleychh** [comment]
Hi @ReflectionGolden, thanks for your message. 
Unfortunately, we did not have this in the past.

Let me clarify your questions. It sounds like you want to set up SSL by accessing environment variables. However, our [Luigi React example](https://github.com/SAP/luigi/tree/master/core/examples/luigi-example-react) is using our [own scripts](https://github.com/SAP/luigi/blob/master/core/examples/luigi-example-react/scripts/start.js) which made environment variables not accessible? 

Have you tried to use [create react app](https://create-react-app.dev/) first, then setup Luigi afterwards?
You could also have a look our [NextJS example](https://github.com/SAP/luigi/tree/master/core/examples/luigi-example-next) for reference.

**Comment by ReflectionGolden** [comment]
Hi, I did try to use create-react-app and setup Luigi after to see if that would work, but when I ran through [The application setup for react](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-react) with the manual set of commands, some of them wouldn't run (the ones that come after the "# replace strings in some places" comment. They give errors about '&&' not being a valid separator in 'this version'), and the others didn't seem to set up correctly.

Also, when trying to run the command above that which is supposed to do it all at once instead gives me an error to do with "The '<' operator is reserved for future use."

Are the commands in this area of the documentation out of date, or otherwise require certain things to work?

**Comment by stanleychh** [comment]
Hi, thanks for your reply.

Yes, the [setup script for react](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-react) seems updated. We will take a look. At the meantime, I would suggest you set up Luigi manually after using create-react-app.

**Comment by ReflectionGolden** [comment]
> Hi, thanks for your reply.
> 
> Yes, the [setup script for react](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-react) seems updated. We will take a look. **At the meantime, I would suggest you set up Luigi manually after using create-react-app.**

I have tried this, and I don't think the manual setup works either.
The files it generates don't look the way they should if the example application is anything to go by. An example of such includes the `sampleapp.html` file showing with content as the following quote:

> StatusCode        : 200
> StatusDescription : OK
> Content           : <!DOCTYPE html>
>                          <html lang="en">
>                          <head>
>                          <meta charset="utf-8" />
>                          <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
>                          <meta name="viewport" content="width=device-width, initial-scale=1" /...
> RawContent        : HTTP/1.1 200 OK
>                              Connection: keep-alive
>                              Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
>                              Strict-Transport-Security: max-age=31536000
>                              X-Content-Type-Options: nosniff
>                              ...
> Forms              : {}
> Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options, nosniff]...}
> Images             : {}
> InputFields       : {}
> Links                : {}
> ParsedHtml        : mshtml.HTMLDocumentClass
> RawContentLength  : 366

all other files generated by the manual commands show up in a similar way, only showing some of the content they should have with information before and after it.

**Comment by ReflectionGolden** [comment]
Some more information you might need: I am trying to do this over windows, but I have been informed the command for the script is for linux. Is there a windows equivalent for this?

**Comment by stanleychh** [comment]
Thanks for your information. Unfortunately, the script was written for Linux only.
We already created a ticket #2640 for fixing the outdated script.

**Comment by stanleychh** [comment]
Hi @ReflectionGolden, I had a look in the [React setup script](https://docs.luigi-project.io/docs/application-setup/?section=application-setup-for-react). The error came from the version of `react-router-dom`. 
The script installed `v6.3.0` of `react-router-dom` which is not compatible to our [react-example](https://github.com/SAP/luigi/tree/master/core/examples/luigi-example-react). 

React example is still using [v5.1.2](https://github.com/SAP/luigi/blob/master/core/examples/luigi-example-react/package.json#L53) which supports hash routing. There are few breaking changes as well.

I would suggest you to clone our [react-example](https://github.com/SAP/luigi/tree/master/core/examples/luigi-example-react) directly and add on your features at this moment. I hope this information is helpful.

**Comment by ReflectionGolden** [comment]
Hi @stanleychh, the reason I was trying to start a new project is because it would likely be automatically using react-scripts instead of custom scripts, as the custom scripts mean that I am finding issues with using certificates because the custom ones don't look at the same environment variables and when I tried to manually change to react-scripts it didn't load the page properly.

**Comment by ReflectionGolden** [comment]
I've found the reason for my original question, it is that the custom scripts (while being seemingly based on the react-scripts) don't include the 'getHttpsConfig.js' file in the configuration folder by default, which means they can't reference the SSL_CRT_FILE and SSL_KEY_FILE environment variables.

**Comment by stanleychh** [comment]
Hi @ReflectionGolden, just a heads-up that our [react-script](https://docs.luigi-project.io/docs/application-setup/?section=application-setup-for-react) is fixed. The react-router-dom version is pinned to v5.

Regarding the SSL issue, will that be helpful if our script includes `getHttpsConfig.js` file? Thanks.

**Comment by ReflectionGolden** [comment]
Hi, I was able to find that the SSL issue was in the lack of `getHttpsConfig.js` file in my project. Thanks for being able to fix this for any future projects and anyone else who will use Luigi in the future.
