### ISSUE TITLE
Getting started material not working when modifying the viewUrl of a children 

### ISSUE THREAD

**Issue by sthepaut** [SAP/luigi#2632]
**Description**
I followed the instruction of 'https://github.com/SAP/luigi/blob/master/docs/getting-started.md' for "Angular "and "no framework" and in both cases the same issue occurred.
After installation and when running the application I have modified in the luigi-config.js to point the Section two child to access my own app url on localhost.
I have also tried to put other urls like 'https://luigi-project.io/' but each time the same buggy behavior.

**Env** 
Windows 10
Chrome Version 99.0.4844.74 (Build officiel) (64 bits)

**Expected result**
See the html content coming from the url in the section area and have it still there as long as no other action is taken.

**Actual result**
What happens is that the content appears during a fraction of second (or very often not at all) and then it disappears and three dots start flickering in the middle of the area indefinitely as if waiting for something to happen (but actually not reacting to any action on this zone).

**Steps to reproduce**
Install, run and modify the url to any local or remotre url and watch.

**Troubleshooting**
After installing the "Angular" version and tried the "no framework" but I have the same issue. 
Changing the url to any other than the static content in assest show the same issue.

**Comment by alexandra-simeonova** [comment]
Hi, if I'm not mistaken this can happen if the micro frontend app does not use [Luigi Client](https://docs.luigi-project.io/docs/luigi-client-setup). (See the second FAQ question here https://docs.luigi-project.io/docs/faq?section=ui-questions). You could try to disable the loading indicator for your navigation node in the luigi-config.js, for example :
```
{ 
    pathSegment: '2', 
    label: 'Child 2', 
    category:  'Section Two',
    loadingIndicator: {
        enabled: false
    },
   viewUrl: 'https://example.com'
}
```

**Comment by sthepaut** [comment]
It works, thanks.
