### ISSUE TITLE
.getCurrentRoute() returns :virtualSegment_1/:virtualSegment_2/:virtualSegment_3

### ISSUE THREAD

**Issue by DenisDuev** [SAP/luigi#2771]
**Description**

Using `LuigiClient.linkManager().getCurrentRoute()` returns `/projects/project1/documentation/:virtualSegment_1/:virtualSegment_2/:virtualSegment_3` instead of the real values as described in the first example #2724

LuigiClient version 1.23.1

**Expected result**

As described in #2724 
LuigiClient.linkManager().getCurrentRoute() - full route of luigi main app, e.g. `/projects/project1/documentation/Product/Contact/Teams`

**Actual result**

`/projects/project1/documentation/:virtualSegment_1/:virtualSegment_2/:virtualSegment_3`

**Steps to reproduce**

In a page with virtual segments call: `LuigiClient.linkManager().getCurrentRoute()`

**Troubleshooting**

`LuigiClient.linkManager().fromVirtualTreeRoot().getCurrentRoute()` also return something strange:
`/projects/project1/documentation` instead of `/Product/Contact/Teams`

**Comment by ndricimrr** [comment]
Hi @DenisDuev , I believe we have spotted this issue and is currently being handled in [this PR](https://github.com/SAP/luigi/pull/2765).

**Comment by ndricimrr** [comment]
@DenisDuev The PR to resolve this was merged. The changes involve Luigi Core. You can already use the fix by updating the Luigi Core version to [the latest nightly build](https://www.npmjs.com/package/@luigi-project/core/v/1.23.2-dev.202206282257). I am closing this issue as the task was merged. Please do re-open it again if there are any issues or questions.

**Comment by DenisDuev** [comment]
Hi @ndricimrr 
I tried again the command. `LuigiClient.linkManager().getCurrentRoute()` seems to work fine, but `LuigiClient.linkManager().fromVirtualTreeRoot().getCurrentRoute()` returns `undefined`

**Comment by ndricimrr** [comment]
Hi @DenisDuev ,
That's definitely not the expected behaviour and I can't seem to reproduce it 🤔 . Which Client/Core version are you currently using ?

**Comment by DenisDuev** [comment]
Sorry, the feature is working as expected. The problem was on my side :)
