### ISSUE TITLE
[User Settings Dialog] Should show user avatar instead of icon

### ISSUE THREAD

**Issue by mengbingguo** [SAP/luigi#2789]
**Description**

The User Settings Dialog should show the user avatar, not an icon.

**Expected result**

![image](https://user-images.githubusercontent.com/75482561/176700433-bb1c3be7-c303-45da-b771-70a2d24624f0.png)

**Actual result**

![image](https://user-images.githubusercontent.com/75482561/176700294-2803201e-76d6-41b2-ad78-6531fc6e9623.png)

**Comment by hardl** [comment]
this is possible but has to be configured on application side (https://docs.luigi-project.io/docs/user-settings)
