### ISSUE TITLE
[User Settings Dialog] Unwanted scrollbar

### ISSUE THREAD

**Issue by mengbingguo** [SAP/luigi#2790]
**Description**

There is an unwanted scrollbar in the User Settings Dialog

**Expected result**

Scrollbar doesn't appear if not needed

**Actual result**

![image](https://user-images.githubusercontent.com/75482561/176702630-33be43ea-ed6e-43eb-81ad-fa349ba13269.png)

**Comment by hardl** [comment]
can be fixed by adding
`line-height: 0` 
to 'iframeUserSettingsCtn' class (https://github.com/SAP/luigi/blob/0fcef6a8874a8536ab9908ab7db414f4e0867c74/core/src/UserSettingsDialog.svelte#L568)
