### ISSUE TITLE
History entry for modals

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2802]
When opening a modal micro frontend and showModalPathInUrl is true (https://docs.luigi-project.io/docs/navigation-parameters-reference/?section=showmodalpathinurl), a browser history entry should be created, so that if the user does a history back, the modal is closed but the main mfe will stay the same.

(extension-manager-189)

**Comment by JohannesDoberer** [comment]
need some discussions

**Comment by JohannesDoberer** [comment]
Blocked because behavior not yet clarified.

**Comment by hardl** [comment]
when opening a modal with `showModalPathInUrl`, store the history length and create a history entry (i.e. using pushstate). when closing the modal, go back in history to the stored state. Double check "re-visit" behaviour, e.g. after page refresh or deeplink with no history.

**Comment by JohannesDoberer** [comment]
Add a `popState` eventListener when calling history.go() and use the option parameter to use it [`once`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener).
- call pushState
- (go forward)
