### ISSUE TITLE
Improve Core unit tests

### ISSUE THREAD

**Issue by parostatkiem** [SAP/luigi#289]
**Description**
For now the unit test coverage is quite low, I'd estimate it to be around 50% which means half of the functions are not tested at all. I discovered it during a refactoring task when there were some missing dependencies but all tests were green (the Angular example didn't even render anything due to Core's errors).

**Reasons**

**Attachments**

**Comment by jesusreal** [comment]
Thanks @parostatkiem, we need an analysis step before improving the tests, so we will follow up on this in scope of the following issue: https://github.com/SAP/luigi/issues/551
