### ISSUE TITLE
Implement ability to refresh env list in ContextSwitcher

### ISSUE THREAD

**Issue by parostatkiem** [SAP/luigi#290]
**Description**
~Luigi Client should provide such a possibility.~

Luigi core api needs a function to refresh options of context switcher.

The microfrontend should then use a custom event defined by the luigi core app (console in this example) to fire a semantic change event, e.g. envChanged or so.

**Reasons**

**Attachments**

**Comment by maxmarkus** [comment]
Fixed with #613 since with enabling **lazyLoadOptions**, it always gets refreshed and caching should be done on user configuration side, if required.
