### ISSUE TITLE
Improve Luigi Client support Angular documentation

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#2904]
Some parts of the Luigi Client support Angular library documentation need to be updated, e.g. [Preload Component](https://docs.luigi-project.io/docs/framework-support-libraries?section=preload-component-example).

**Comment by ndricimrr** [comment]
- Change "Preload component example" => "Angular Routing Example"

- Preload component (<--**Remove this hyperlink**) - an empty Angular component that can be used to build a preload...

I think this could be a fix for this.
