### ISSUE TITLE
Update 3rd party cookie check with samesite attribute

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2919]
Add `SameSite=None; Secure` to the luigi client cookie otherwise `SameSite=Lax` will be used (default value).
https://github.com/SAP/luigi/blob/master/client/src/lifecycleManager.js#L156

**Comment by paschdan** [comment]
additionally it needs to be updated here:

https://github.com/SAP/luigi/blob/fa9031e8fd1734058d2dd2ba03fe4d6b68688133/core/third-party-cookies/init.html#L16
