### ISSUE TITLE
Investigate Angular setup broken build

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#2951]
Test setup script [build](https://app.travis-ci.com/github/SAP/luigi/builds/257241207) fails on the Angular Setup. Investigate if the angular setup is broken or not.

**Comment by alexandra-simeonova** [comment]
I got this error while trying to install from the [Angular script](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-angular):

<img width="1300" alt="Screen Shot 2022-11-02 at 11 13 51" src="https://user-images.githubusercontent.com/49867570/199464062-3f287c9b-428e-4c0b-92f4-85d1e85a7169.png">
