### ISSUE TITLE
Need to click browser back button twice after closing a modal to navigate back

### ISSUE THREAD

**Issue by MalteBellmann** [SAP/luigi#2983]
**Description**

After closing a modal using the `X` in the top right corner, navigating back takes two clicks on the browser back button. 

`"@luigi-project/core": "1.25.2-dev.20221180015",`

**Expected result**
Directly after the first click the browser navigates back.

**Actual result**
You need to click twice to trigger the navigation.

**Steps to reproduce**
1. Navigate to page 1
2. Navigate to page 2
3. Open a Luigi modal
4. Close it using the `x` button
5. Click browser back button => nothing happens
6.  Click browser back button again => navigation triggers

**Troubleshooting**

**Comment by JohannesDoberer** [comment]
Fixed with v1.26.0
