### ISSUE TITLE
Update luigi-example-openui5

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2993]
Update all libraries in core/examples/luigi-example-openui5 to latest stable versions.

**Comment by ndricimrr** [comment]
:warning: Latest ui5 3.0 cli requires nodejs/npm >=**16 || 18**

**Comment by somabagyinszky7** [comment]
Hi @JohannesDoberer, @ndricimrr,
I would be happy to work on this / look into this.

**Comment by ndricimrr** [comment]
Hi @somabagyinszky7 . Feel free to take it.
