### ISSUE TITLE
Investigate documenting General Slack channel

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3006]
As our general slack channel history is limited, it doesn't allow to search for old questions. After X number of days the discussion questions are lost producing repetitive work. Investigate a better way to manage it so we don't loose the discussions.

**Comment by alexandra-simeonova** [comment]
Some suggested options: 
1. Copy questions from Slack to [GitHub Discussions](https://github.com/SAP/luigi/discussions)
- Pro: preserve questions in a public place
- Con: Different formats + we have to "answer our own questions" or ask people to double-post the same thing on Slack/GitHub

2. Create a Discord channel
- Pro: no expiry date for messages
- Con: one more channel to monitor

**Comment by alexandra-simeonova** [comment]
Microsoft Teams (the SAP most commonly used platform) is planning to create an external (similar to Discord) messaging service as well: https://www.microsoft.com/en-us/microsoft-365/blog/2022/12/07/communities-in-microsoft-teams-connect-collaborate-and-share/
However, it's not released for corporate clients yet.

**Comment by alexandra-simeonova** [comment]
The archive of the Slack channel is available on the Luigi Wiki under **Internals > Slack archive**
