### ISSUE TITLE
Fix documentation broken Link for UI5 icon

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3015]
On https://docs.luigi-project.io/docs/navigation-parameters-reference/?section=icon
> .... Its source may be OpenUI or a custom link (relative or absolute) to an image. ....

Link to relative **OpenUI** seems broken.

Also **OpenUI** should be **OpenUI5** instead. 

Suggested working link: 
https://sapui5.hana.ondemand.com/sdk/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons

**Comment by JohannesDoberer** [comment]
Probably duplicated #3008

**Comment by ndricimrr** [comment]
my bad 😅
