### ISSUE TITLE
React script not working 

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#3071]
The react script at  https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-react does not work for me and a customer when following these steps: 

- Open Terminal
- Go to a local folder
- Run the script from the documentation `bash <(curl -s https://raw.githubusercontent.com/SAP/luigi/master/scripts/setup/react.sh)`
- Application seems to be installed, but only a blank page opens on localhost:3000

However, if you directly install the React example from https://github.com/SAP/luigi/tree/master/core/examples/luigi-example-react, it starts normally.

**Comment by ndricimrr** [comment]
Needs some more context as I was not able to reproduce on the latest master branch version so far.

**Comment by alexandra-simeonova** [comment]
The steps I followed were:
1. Open Terminal
2. Go to a local folder on my computer
3. Run the script from the documentation `bash <(curl -s https://raw.githubusercontent.com/SAP/luigi/master/scripts/setup/react.sh)`
4. Application seems to be installed, but only a blank page opens on `localhost:3000`

My npm version is: 
npm: '8.19.2',
node: '16.18.1'

**Comment by alexandra-simeonova** [comment]
![Screenshot 2023-02-27 at 10.43.30.png](https://images.zenhubusercontent.com/5d5bb1912298e3000103e6e2/bef8e6ef-97c7-464a-a703-50690a62c9a8)

**Comment by somabagyinszky7** [comment]
Hi @alexandra-simeonova,
Do you have any updates about this? Do you know if this is still a relevant issue?
I also cannot reproduce the problem on my side.
Are you or the client receiving an error output in the terminal?

**Comment by alexandra-simeonova** [comment]
> Hi @alexandra-simeonova, Do you have any updates about this? Do you know if this is still a relevant issue? I also cannot reproduce the problem on my side. Are you or the client receiving an error output in the terminal?

Hi, I was able to resolve this issue by switching to a different Node version (the one I currently have is v18.12.1).
There was no error output previously.
I will close this issue since it is also working on your side.
