### ISSUE TITLE
Tabnav: navigate on click on category dropdown

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3197]
Allow to click on a "category" tab in tabnav and navigate to a specified node with the category. The node can also be hidden.
Possible example config:

```
 ...
   tabNav: true,
   children: [{
      pathSegment: 'seg'
      viewUrl: 'foo.bar',
      //hideFromNav: true,
      category: {
         label: 'Cat',
         navigateOnClick: true // OR a string with the path segment, e.g. 'seg'
      }
   }]
...
```
Corner case: if this option is configured and the alias node is hidden and the only node, tab should be rendered like single node (i.e. no dropdown)

Use tab with multi click area https://sap.github.io/fundamental-styles/?path=/docs/components-icon-tab-bar--text-only#navigation-icon-tab-bar--shell-navigation-
![image](https://user-images.githubusercontent.com/7690363/220643218-01d55ecd-e2a0-461f-9408-9a1009b3508a.png)

**Comment by JohannesDoberer** [comment]
Blocked: https://github.com/SAP/fundamental-styles/issues/4336
