### ISSUE TITLE
Console error on clicking on "No" in the confirmation dialog

### ISSUE THREAD

**Issue by aaasarthak** [SAP/luigi#3229]
**Description**

- I have a form in my client(microfrontend application), where if the user doesn't save before navigating I want to give a confirmation dialog for the unsaved changes.
- For which I am using `setDirtyStatus()` in the client application which gives the confirmation dialog if the user tries to navigate from the shellbar navigation options.
- But if we click on "No" in the confirmation dialog, it closes the dialog with a console error.

**Expected result**

It should not throw the console error on selecting "No" in the confirmation dialog

**Actual result**

It throws the console error

**Steps to reproduce**

- setDirtyStatus as true from your microfrontend
- Try navigating outside the application
- There will be a confirmation modal to tell that unsaved changes will be lost
- Select "No" on that model
- Observe that the dialog closes and application behavior is as expected, but there is an error in the console.

**Screenshots**

![image](https://user-images.githubusercontent.com/45348322/225860974-6025d70d-d880-4057-a151-2c6c54a02c97.png)
![image](https://user-images.githubusercontent.com/45348322/225861086-ed428e75-45f5-46db-8bdc-5b253387839c.png)

**Comment by ndricimrr** [comment]
Hi @aaasarthak . This issue should be resolved on the next release. Alternatively, you can use the next nightly release for **luigi-project/core** as of tomorrow.
