### ISSUE TITLE
No confirmation dialog on browser reload when dirtyState is set to true

### ISSUE THREAD

**Issue by aaasarthak** [SAP/luigi#3230]
**Description**
When the `dirtyStatus` is set to true, the browser back button shows the confirmation dialog but the browser reload doesn't.

browser used - Chrome

**Expected result**

On click of browser reload also, it should show the confirmation dialog for unsaved changes

**Actual result**

No confirmation dialog

**Steps to reproduce**

- use `setDirtyStatus()` to set the dirty status of the client 
- Try reloading the page using browser reload button
- Observe that there is no confirmation dialog for unsaved data changes

**Comment by JohannesDoberer** [comment]
Hello @aaasarthak ,
we expose a core-api function where you can check which dirty status is currently set and e.g. avoid reloading the page.
Let me know if this helps you.
