### ISSUE TITLE
Show warning when label not defined

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3259]
When label is not defined on a node, the node is not rendered by default. We show warning when **viewUrl** is not defined.
Discuss adding one for label as well.

**Comment by tymnec** [comment]
Hi @ndricimrr I would like to work on this issue. 
**Please assign this to me!**

**Comment by ndricimrr** [comment]
Hi @tymnec . Thanks for picking this up. 

We discussed with the team shortly and this might need some more refinement on where and when it should show the warning.

There is one issue which I can suggest to pick.
https://github.com/SAP/luigi/issues/3263

This should be good to go. Let me know if you want me to assign it to you. Or you can assign it on your own if it is possible

**Comment by ndricimrr** [comment]
Assigned. Feel free to work on it
