### ISSUE TITLE
Splitview not opening with topnav header disabled

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3266]
Set **settings.header.disabled** to true, and try opening the splitview

`Luigi.navigation().openAsSplitView('/home')`

Following error shows.

```
bundle.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'clientHeight')
    at Object.getContentAreaHeight (bundle.js:2:269782)
    at Object.open (bundle.js:2:257734)
    at pe (bundle.js:2:614100)
    at bundle.js:2:628333
```

Error doesn't show when header disabled is false.

**Comment by somabagyinszky7** [comment]
Hi @ndricimrr,
I have found a possible solution to this.
I still have to test it. Then I will create a pull request.
