### ISSUE TITLE
update fundamental styles version

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3330]

**Comment by lpgarzonr** [comment]
Luigi is using fundamentals [styles version 0.26.5](https://github.com/SAP/luigi/blob/01e7517dbe33a6e5c2896ab4048c9d0414f604e4/core/package.json#L12), that version set the avatar [color to --sapContent_ContrastTextColor](https://github.com/SAP/fundamental-styles/blob/c7454c32cfd1516d7781afd752f6e06396259c64/packages/styles/src/avatar.scss#L20C46-L20C46) which is white, this variable does not look that nice for the Horizon theme. The latest version is using the expected the variable [color to fdAvatarColor](https://github.com/SAP/fundamental-styles/blob/1e7d1690ac21bd1053853d23991cb1d8484ef4f9/packages/styles/src/avatar.scss#L20C3-L20C31) improving the contrast of the avatar.

**Comment by JohannesDoberer** [comment]
There is already a draft PR #3486
