### ISSUE TITLE
consistent attribute naming for luigi container

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3397]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2dDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--816454e56a98eee6a2a03f990d32e404c9997b00/image.png)

(virtual) camel-case vs. dash vs. underscore
html boolean conventions https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

**Comment by JohannesDoberer** [comment]
https://svelte.dev/docs/custom-elements-api#component-options
