### ISSUE TITLE
client-support-angular: Provide a more accurate return type for LuigiContextService.getContext

### ISSUE THREAD

**Issue by moxaj** [SAP/luigi#3398]
**Description**

Within the `client-support-angular` library, the [`LuigiContextService.getContext`](https://github.com/SAP/luigi/blob/459e74bff56ba3337c825fdd9069e2f33ea9db1c/client-frameworks-support/client-support-angular/projects/client-support-angular/src/lib/service/luigi-context-service.ts#L11-L14) function specifies its return type as `Context`. However, as its documentation indicates, the returned value can be `null` or `undefined`, which should be reflected in the return type (making it `Context | null | undefined`).

**Reasons**

Doing so would make it less awkward to deal with in typescript.

**Comment by moxaj** [comment]
In my humble opinion, this change actually made it worse :(. Before, I could use undefined checks or optional chaining, even though the type was promised not to be null/undefined (by the typescript compiler at least). Now, to check whether the context is available, I have to do something like `Object.keys(context).length === 0`. Perhaps this empty object idiom is common for the luigi project, but if not, please reconsider simply returning undefined and marking the return type as `Context | undefined`.

**Comment by JohannesDoberer** [comment]
Hello @moxaj, yes it is common for the luigi project to return an empty object. 
Sorry that the change does not meet your expectations.

**Comment by hardl** [comment]
Hi @moxaj, why don't you use contextObservable or getContextAsync? Then you don't have to check at all, if context is already available.
