### ISSUE TITLE
[modalParams]: After updating modal Params, query parameters are not updated

### ISSUE THREAD

**Issue by MichaelBaySAP** [SAP/luigi#3433]
In our project ,we change the size of the modal in our code but it is not updated in the query parameters. Therefore, when refreshing the page, the page returns always to fullscreen size, even if we change the size before. This has led to confusion.

To reproduce this problem, please contact me in a private message as due to confidentiality, information to our service cannot be shared here.

**Comment by JohannesDoberer** [comment]
Issue: old luigi core version in core application.
Conversation in private chat.
