### ISSUE TITLE
Optional pathSegment for the main node

### ISSUE THREAD

**Issue by sobkowiakt** [SAP/luigi#3442]
**Description + code samples and screenshots**
I have the following navigation structure:
```
{
            pathSegment: "home",
            label: "home",
            hideFromNav: true,
            tabNav: true,
            hideSideNav: true,
            children: [{
                pathSegment: "SampleApp1",
                label: "SampleApp1",
                viewUrl: 'https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html',
                context: {
                    title: 'Sample app 1',
                    content: 'Coming soon...'
                }
            }, {
                pathSegment: "SampleApp2",
                label: "SampleApp2",
                viewUrl: 'https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html',
                context: {
                    title: 'Sample app 2',
                    content: 'Coming soon...'
                }
            }]
        }
```
When I run the app everything works fine:
![image](https://github.com/SAP/luigi/assets/145663427/d53ef37e-e133-4d92-8639-5c1245a0d3b6)

**REQUESTED CHANGE:**
Would it be possible to make the main node **pathSegment** property **optional**? If I leave the **pathSegment** property blank I get an error:
```
{
            pathSegment: "",
            label: "home",
            hideFromNav: true,
            tabNav: true,
            hideSideNav: true,
            children: [{
                pathSegment: "SampleApp1",
                label: "SampleApp1",
                viewUrl: 'https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html',
                context: {
                    title: 'Sample app 1',
                    content: 'Coming soon...'
                }
            }, {
                pathSegment: "SampleApp2",
                label: "SampleApp2",
                viewUrl: 'https://fiddle.luigi-project.io/examples/microfrontends/multipurpose.html',
                context: {
                    title: 'Sample app 2',
                    content: 'Coming soon...'
                }
            }]
        }
```
![image](https://github.com/SAP/luigi/assets/145663427/f52a7b96-d9ad-4e3e-845b-9ed8688e1074)

**Reasons**
By adding this possibility the URL can be reduced if there is no need to use the **home** node.
So for instance instead of the _/public/index.html#**/home**/SampleApp1_ there will be only _/public/index.html#/SampleApp1_ URL.

**Comment by JohannesDoberer** [comment]
Hello @sobkowiakt,
we released (v2.7.0) a new feature on node configuration in the section **navigation parameters reference** in our docu, called [topNav](https://docs.luigi-project.io/docs/navigation-parameters-reference?section=topNav).
With this feature your above request is possible.

Cheers, Johannes
