### ISSUE TITLE
Tab-style navigation

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#348]
Luigi core applications with only a few navigation nodes might want to render navigation entries within a horizontal tab-bar below the shell header instead of left-side navigation to free up some space. This should be a configurable option in luigi navigation configuration.

**Comment by JohannesDoberer** [comment]
```
{
  children: [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}],
  context: {currentProject: "tabNav"},
  label: "Horizontal Navigation Example",
  navigationContext: "project",
  parent: {pathSegment: "projects", label: "Projects", viewUrl:"/sampleapp.html#/projects",children:[{...},{...}]},
  pathSegment: "tabNav",
  viewUrl: "/sampleapp.html#/projects/tabNav",
  tabNav: true,
  hideSideNav: true
}
```
Expected behaviour:
-> LeftNav is hidden, children of this node are rendered in TabNav
-> children of children are not rendered (supported)
```
tabNav:true,
hideSideNav:false
```
Expected behaviour:
-> LeftNav is shown with this node (+siblings), children of this node are rendered in TabNav
