### ISSUE TITLE
Container: Investigate timing issue when setting props

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3497]
when setting properties of a luigi-[compound-]container instance by e.g. myContainer.compoundConfig = { foo: 'bar' } BEFORE the registration in the customElementsRegistry is finished, the props are not mapped to the internal svelte variables.
In such a case, here https://github.com/SAP/luigi/blob/ca0bd59b6e6080ebc715123d945e4de5c809f0c8/container/src/LuigiCompoundContainer.svelte#L91
```
 const initialize = (thisComponent: any) => {
    if (!compoundConfig || containerInitialized) {
      return;
    }
```
`compoundConfig` would be undefined, however `thisComponent.compoundConfig` has the correct value.

Could be a svelte issue...

**Comment by hardl** [comment]
To avoid this issue, one use the following:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0afaa9193084a598a34791e95f16d48c04d5b35c/image.png)

**Comment by JohannesDoberer** [comment]
https://github.com/sveltejs/svelte/issues/9487
