### ISSUE TITLE
Angular example does not work

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3499]
**core/example/luigi-example-angular** does not work.
In addition please update update the luigi dependencies.

**Comment by alexandra-simeonova** [comment]
Trying to install the Angular example using the script from https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-angular 
also does not work, at least for me (see error message below) 

<img width="1090" alt="Screenshot 2023-11-02 at 11 47 12" src="https://github.com/SAP/luigi/assets/49867570/a69a420f-11fa-41c4-b984-5f18be631404">

**Comment by ndricimrr** [comment]
Two things need to be checked: 

1. That the example in the folder works:
```
cd core/example/luigi-example-angular 
npm install
npm start
```

2. That the bash script mentioned above works:
`bash <(curl -s https://raw.githubusercontent.com/SAP/luigi/main/scripts/setup/angular.sh)`
(hint: Replace URL `https://raw.githubusercontent.c.../main/.../angular.sh` with the one from the PR to be opened  ex: `https://raw.githubusercontent.c.../my-new-branch/.../angular.sh`)

Steps 1 and 2 depend on each other, so starting with 1 and then fixing 2 if there's still issues.
