### ISSUE TITLE
Outdated links in docs for authorization

### ISSUE THREAD

**Issue by camelCaseChris** [SAP/luigi#3517]
**Description**

I found dead links in the [authorization documentation](https://docs.luigi-project.io/docs/authorization-configuration?section=custom-authorization-provider):
- ​[oAuth2ImplicitGrant.js](https://github.com/SAP/luigi/blob/main/core/src/providers/auth/oAuth2ImplicitGrant.js)
- [openIdConnect.js](https://github.com/SAP/luigi/blob/main/core/src/providers/auth/openIdConnect.js)

**Expected result**

Links should work.

**Actual result**

HTTP 404 Not Found

**Steps to reproduce**

**Troubleshooting**

**Comment by ndricimrr** [comment]
Needs to discuss how to refactor docu since the outdated links point to files (**oAuth2ImplicitGrant.js**,
**openIdConnect.js**) which were not present after https://github.com/SAP/luigi/pull/1201
