### ISSUE TITLE
Flaky test in Backwards Compatibility Check

### ISSUE THREAD

**Issue by camelCaseChris** [SAP/luigi#3587]
**Description**

There seems to be a flaky test in Backwards Compatibility Check -> Compatibility Tests. Workflow run https://github.com/SAP/luigi/actions/runs/7183356971 was initially reported as failed. After running it again, it went through successfully.

**Comment by JohannesDoberer** [comment]
Probably duplicated with #3724.
I'll close this issue because logs can't be displayed anymore.
