### ISSUE TITLE
blog post release 2.8.0

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3619]

**Comment by JohannesDoberer** [comment]
🚀 Added
#3590 Lazy loading option for compound web component mode (@camelCaseChris)
🐛 Fixed
#3572 Calc max-height for tabNav dropdown (@JohannesDoberer)
#3564 Fix resizing when drawer opens/closes (@camelCaseChris)

**Comment by ndricimrr** [comment]
Resolved in #3619
