### ISSUE TITLE
Update angular support lib to angular v17

### ISSUE THREAD

**Issue by sarthak505** [SAP/luigi#3625]
Is there any plan for angular v17 support? We want to upgrade our application.

**Comment by sarthak505** [comment]
> Hello @sarthak505, yes it it planed. There is already a PR #3623. I'll let you know when we have released it.

Sure, thanks!

**Comment by JohannesDoberer** [comment]
Hello @sarthak505,
we released luigi v2.9.0. With that we support angular v17.

Cheers
