### ISSUE TITLE
Automate Changelog Generation for container & standalone libraries

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3631]
Should be just one simple command:
 
example: 
```
// changelogGeneration.js
lerna-changelog --from=v2.8.0 --to=v2.8.1 --lerna-label=container
or
lerna-changelog --from=v2.8.0 --to=v2.8.1 --lerna-label=ui5-support-library
```

Also each PR that adds new features and fixes bugs (ignore internal fixes/docu/refactoring not relevant to client) should have the **"container"** or  **"ui5-support-library"** label, or any other label names.

**Comment by JohannesDoberer** [comment]
UI5 support lib will be handled in a different PR
