### ISSUE TITLE
Remove third-party-cookie check functionality

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3641]
...as they will be blocked anyway by all major browsers.

Potentially a breaking change -> https://docs.luigi-project.io/docs/general-settings/?section=third-party-cookies-support-check

**Comment by walmazacn** [comment]
Here's official timeline for changes in Chrome - https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

MS Edge has similar plans, but official timeline is not published yet - more info:
https://blogs.windows.com/msedgedev/2024/03/05/new-privacy-preserving-ads-api/
