### ISSUE TITLE
Puppeteer support for testing-utilities lib

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3645]
Follow up of #3611 and #3644

This issue is a part of https://github.com/SAP/luigi/issues/3612 epic

**Comment by walmazacn** [comment]
It seems Puppeteer doesn't expose access to real window object like in Cypress - they patch it with their own API. The only way to access active window is through evaluate method, but it's more like encapsulated mode:
https://pptr.dev/api/puppeteer.page.evaluate
