### ISSUE TITLE
Add new scope "navigation.context" to Luigi.configChanged()

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#3685]
When Luigi.configChanged('navigation.context') is called, it should trigger the invocation of the contextUpdateListeners (context setter for web components) at the micro frontends with the (potentially updated) context.

See: https://docs.luigi-project.io/docs/luigi-core-api/?section=configchanged

**Comment by JohannesDoberer** [comment]
After discussion with Philipp we will introduce a new function in core api where you can update the context.
