### ISSUE TITLE
Blank section on top when upgrading to 1.2.0-rc1

### ISSUE THREAD

**Issue by clabnet** [SAP/luigi#3694]
Hi, 
is there a strange issue when upgrading `@luigi-project/container` to version `1.2.0-rc1`. 
The top of container area is blank, and the content it shifted to bottom, causing a vertical shift of the visible area. 
Downgrading to `@luigi-project/container": "1.1.0"`, the problem goes away.
It is normal that? 
![image](https://github.com/SAP/luigi/assets/6067610/3762c0a5-6cd9-4fa6-943f-aa8e931d3d5e)

**Comment by hardl** [comment]
probably related to https://github.com/sveltejs/svelte/issues/10454

**Comment by hardl** [comment]
@clabnet please check again with 1.2.0-rc2

**Comment by clabnet** [comment]
@hardl   It works. 
Many thank's, your support is fantastic.
