### ISSUE TITLE
UI5 WC Demo in Luigi Fiddle is broken

### ISSUE THREAD

**Issue by ok** [SAP/luigi#3698]
**Description**

The UI5 Web Component documentation in Luigi Fiddle is broken. 

- macOS
- Chrome (latest)

**Expected result**

UI5 WC demo loads correctly

**Actual result**

UI5 WC demo doesn't load, shows issue with loading bundle.esm.js from UI5 Web Components documentation. (likely related to the latest changes in UI5 doc tooling)

<img width="878" alt="Screenshot 2024-04-15 at 17 48 40" src="https://github.com/SAP/luigi/assets/54379826/677134f9-29dd-49b5-8778-97df2557896d">

**Steps to reproduce**

Open [Luigi Fiddle for UI5 Web Components](https://fiddle.luigi-project.io/#/home/wc3)

**Comment by hardl** [comment]
Indeed related to changes in UI5 doc tooling...
Contacted the colleagues and waiting for replacement
