### ISSUE TITLE
Check Core bundle size warning when building code locally

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3703]
<img width="834" alt="Screenshot 2024-04-18 at 18 32 58" src="https://github.com/SAP/luigi/assets/18335489/d488c0f9-941a-4c0e-9c9f-38aa086f9145">

Investigate where it comes from or when. Can we disable the warning or increase the limit or somehow decrease the size altogether

**Comment by walmazacn** [comment]
It comes from Vite config where 'chunkSizeWarningLimit' is set to 530 kB - what's interesting, in 'bundlesize' script limit for reported 'luigi.js' file is set to 650 kB and its original size on Windows is 519 kB ('core/public/luigi.js')

Possible solutions - either we increase the limit in Vite config or investigate how to decrease the size of 'luigi.js' file
