### ISSUE TITLE
Nightwatch support for testing-utilities

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3765]
This issue is a part of https://github.com/SAP/luigi/issues/3612 epic

**Comment by walmazacn** [comment]
It seems Nightwatch doesn't expose access to real window object - they patch it with their own API. The only way to access the window is through 'executeScript' method, but it's more like read-only mode and we can't use 'LuigiMockUtil' in this context:
https://nightwatchjs.org/api/document/executeScript.html

As testing utilities rely on window object it might be impossible to support Nightwatch at the moment

**Comment by walmazacn** [comment]
Closing the issue for now
