### ISSUE TITLE
WebdriverIO support for testing-utilities

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3766]
This issue is a part of https://github.com/SAP/luigi/issues/3612 epic

**Comment by walmazacn** [comment]
It seems WebdriverIO doesn't expose access to real window object like in Cypress - they patch it with their own API. The only way to access the window is through `execute` method, but it's more like encapsulated mode and we can't use 'LuigiMockUtil' in this context:
https://webdriver.io/docs/api/browser/execute

As testing utilities rely on window object it might be impossible to support WebdriverIO at the moment

**Comment by walmazacn** [comment]
Closing for now
