### ISSUE TITLE
Release script for classic luigi replaces nextrelease placeholder in container

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3804]
When we run **./tools/release-cli/replaceInAllFiles.sh "NEXTRELEASE" "X.XX.X"** like described in the **./scripts/tools/release-cli/release-cli.js** script, the md files in container will also be touched.
This should not be the case because container has its own release cycle.

**Comment by ndricimrr** [comment]
The script works fine. The label is mistaken in container. 
I [made them](NEXT_RELEASE) different to differentiate them, but that was not a very good name pick it seems :D 
**NEXTRELEASE** - General release
**NEXT_RELEASE** - Container release 

Need to change '**NEXTRELEASE**' string instances for `container/` docs to **'NEXT_RELEASE'**. But better than that might need to make the string **NEXT_RELEASE_CONTAINER** to avoid further confusion.

**Comment by JohannesDoberer** [comment]
Thx for clarification, my mistake!
But yes, we should call it what you suggested to avoid this confusion again :)
