### ISSUE TITLE
Tutorial UI5 + Luigi Container Improvements

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3816]
Improvments for our [UI5 Luigi Container Improvements](https://developers.sap.com/tutorials/luigi-container.html) 

-> ui5 yaml file: wrong **afterTask**, should be **replaceVersions** instead of **generateVersionInfo**

**Comment by smahati** [comment]
will be fixed by https://github.com/sap-tutorials/Tutorials/pull/23655
