### ISSUE TITLE
Update dependencies for /scripts folder

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#3819]
Folder has some outdated packages used mainly to generate documentation.

The [package](https://www.npmjs.com/package/documentation) "**documentation**" is the culprit.

Currently at version 11. 

Would be ideal to migrate to v14. This however causes major breaking changes all accross our documentation by breaking a lot of styling. Discuss if this is worth the task or not. Alternatively can choose to override nested dependencies which are outdated.

**Comment by walmazacn** [comment]
Related issue - https://github.com/SAP/luigi/issues/2276
