### ISSUE TITLE
No icon in alert in >=2.9.0

### ISSUE THREAD

**Issue by darvsorceix** [SAP/luigi#3821]
**Description**

After version 2.9.0 showAlert has no icon on the left side of Alert (seems removed from styles). It works correctly on 2.8.0.

**Expected result**

Alert should contain icon

![image](https://github.com/user-attachments/assets/838be355-2cf0-485b-b30a-d03bfebde9a3)

**Actual result**

![image](https://github.com/user-attachments/assets/54909355-9181-4586-a2d0-10387a14362a)

**Steps to reproduce**

Create default alert on vanillia javascript example:

```
  document.addEventListener('DOMContentLoaded', function() {
    const settings = {
      text: 'Ut enim ad minim veniam, {goToHome} quis nostrud exercitation ullamco {relativePath}. Duis aute irure dolor {goToOtherProject}',
      type: 'info',
      links: {
        goToHome: { text: 'homepage', url: '/overview' },
        goToOtherProject: { text: 'other project', url: '/projects/pr2' },
        relativePath: { text: 'relative hide side nav', url: 'hideSideNav' },
        neverShowItAgain: { text: 'Never show it again', dismissKey: 'neverShowItAgain' }
      },
      closeAfter: 10000
    };
    LuigiClient
      .uxManager()
      .showAlert(settings)
    ;
  });
```

**Comment by walmazacn** [comment]
Indeed this issue was introduced after Fundamental styles upgrade in version 2.9.0:
https://github.com/SAP/luigi/pull/3486/files#diff-7f67769260741e2563407af949f7e54fbf0431d1c607933f6e8a8094e3219e26L12
