### ISSUE TITLE
Investigate vendor prefixes still needed

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3837]
Investigate whether vendor prefixes are still needed or which ones we can get rid of.

**Comment by walmazacn** [comment]
The following CSS properties are included in source CSS files and have some prefixes - some of them don't need it anymore, but other still do (according to "caniuse.com"):
- 'animation' - no prefixes
- 'appearance' - no prefixes
- 'border-radius' - no prefixes
- 'box-shadow' - no prefixes
- 'font-smoothing' - moz, webkit
- 'keyframes' - no prefixes
- 'overflow-scrolling' - webkit
- 'scrollbar' - webkit
- 'text-size-adjust' - webkit
- 'text-stroke' - webkit
- 'transform' - no prefixes
- 'transition' - no prefixes
- 'user-select' - webkit

**Comment by walmazacn** [comment]
This task should be handled after another one - https://github.com/SAP/luigi/issues/3824
