### ISSUE TITLE
Test allowRules for LuigiContainer

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3843]
Provide unit tests and e2e tests when the attribute `allowRules` is defined.

```
<luigi-container viewUrl="/multipurpose.html" allow-rules='["fullscreen", "microphone", "camera \"none\"", "geolocation \"self\" https://a.example.com https://b.example.com"]'></luigi-container>
```

--

This issue is part of https://github.com/SAP/luigi/issues/3757

**Comment by ndricimrr** [comment]
Addressed in https://github.com/SAP/luigi/pull/3852
