### ISSUE TITLE
Update peer dependency for client-support-angular

### ISSUE THREAD

**Issue by vladm9800** [SAP/luigi#3869]
**Description**

Could you add version 18 of Angular to the peer dependencies? [client-support-angular](https://github.com/SAP/luigi/tree/main/client-frameworks-support/client-support-angular/projects/client-support-angular#L10-L11)

**Reasons**

At the moment this is blocking us from upgrading to Angular v18

**Comment by JohannesDoberer** [comment]
Hello @vladm9800,
with version Luigi v2.15.0 you get angular 18 support. We released it right now.

Cheers,
Johannes
