### ISSUE TITLE
Docs website: styling issues

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#4060]
1. mobile breakpoint
![image](https://github.com/user-attachments/assets/783f5623-185a-46f3-9df9-43c815c46d49)

2. clicking on global search does not set input focus on search input field

3. focus outline for top entries have strange spacings  
![image](https://github.com/user-attachments/assets/f55c24e4-5482-4574-8fc2-00b5bc5192bb)

**Comment by walmazacn** [comment]
Also button for switching left nav on mobile seems to be broken:

![Screenshot 2024-12-12 133042](https://github.com/user-attachments/assets/0661147d-de97-462d-8fb5-efb1288a37d6)
