### ISSUE TITLE
Provide Typescript Module Template File for Client

### ISSUE THREAD

**Issue by sbgreene1307** [SAP/luigi#418]
**Description**
Currently, there is no module template (*.d.ts file) for the Luigi Client, which causes linting issues in our project.

Reproduce:
In an Angular 7 project, install the LuigiClient dependency and in the app.component.ts file have the content.
```
import { Component, OnInit } from '@angular/core';
import LuigiClient from '@kyma-project/luigi-client';
import { ILuigiContextTypes, LuigiContextService } from './services/luigi-context.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {

  public luigiClient: LuigiClient = LuigiClient;

  //
  // Angular Lifecycle Methods
  //
  constructor(private luigiService: LuigiContextService) {
  }

  // On Component Initialization
  ngOnInit() {
    this.luigiClient.addInitListener(context =>
      this.onLuigiContext('init', context)
    );
    this.luigiClient.addContextUpdateListener(context =>
      this.onLuigiContext('update', context)
    );
  }

  private onLuigiContext(contextType: ILuigiContextTypes, context: any): void {
    this.luigiService.setContext({ contextType, context });
  }
}
```

Note that the this.luigiClient.addInitListener and this.luigiClient.addContextUpdateListener methods are unknown and thus cause linting errors. 

**Reasons**
To provide type safety for projects that implement the luigi client.

**Attachments**

**Comment by jesusreal** [comment]
To avoid breaking backwards compatibility, more precisely to avoid Typescript apps linting and/or compilation fail due to the addition of the Typescript declaration file for Luigi Client, in #466 we have temporarily deactivated this file.
We will discuss about the best solution to introduce this change in Luigi with the lowest impact for our users.

**Comment by maxmarkus** [comment]
Also think about how we can make sure the client api stays in sync with template file.

**Comment by JohannesDoberer** [comment]
Due to our backlog cleanup we will close this issue.
