### ISSUE TITLE
Popover Notification Icon with Counter in Header 

### ISSUE THREAD

**Issue by santoshkpragiti** [SAP/luigi#420]
**Description**
Is it possible to add PopOver Notification icon link in Header to showcase all previous users notifications (Error/ Success/ Info). 
I.e. using a small icon next to the user logout button which opened an overlay to view old messages. The Icon should indicate, that there are messages and error messages.  
For example: https://sap.github.io/fundamental/demo-pages/full-width-app-demo.html

**Reasons**
To user to view older error messages again. 

**Attachments**
https://sap.github.io/fundamental/demo-pages/full-width-app-demo.html
https://sap.github.io/fundamental/components/popover.html

**Comment by lszymik** [comment]
@hardl Can you please check it? Thank you.

**Comment by maxmarkus** [comment]
Split into two tasks: 
#574 Dropdown functionality for top nav nodes
#562 Counter Badges for top nav nodes

**Comment by maxmarkus** [comment]
Available with 0.5.x
