### ISSUE TITLE
console.error in header.js for src on login auth redirect

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#485]
When clicking on re-login after logging out (using oidc mock for example), the console.error `cannot set property src of undefined` in header.js is thrown.

<img width="749" alt="screen markus e 2019-04-15 at 16 04 51" src="https://user-images.githubusercontent.com/1720843/56139126-84408780-5f98-11e9-8bd7-50a8db73369d.png">

Reproduce: 
1. example app login
2. log out
3. click on login again
4. check console

**Comment by marynaKhromova** [comment]
I can't reproduce this issue. @maxmarkus Could you please check again if it's still relevant?
