### ISSUE TITLE
Refactor Authentication not to rely on localstorage luigi.auth object.

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#487]
For OAuth2 it is fine to use luigi.auth, but other providers should not rely on that object.
Needs a deep look on how we want to refactor.

To think about:  
- existing implementations rely on `luigi.auth` in localStorage (for showing logged in state as well as logout behaviour)
- there might be providers upcoming with cookie sessions and without any tokens or auth data in the frontend
- existing customers are relying on `luigi.auth` in localStorage (at least for OAuth2), don't break them
- Luigi core could expose some authManager helpers for setting states like logged in, storing  and fetching auth data.

Related to: #489

**Comment by maxmarkus** [comment]
Implementation should wait for bootstrap refactoring.

**Comment by JohannesDoberer** [comment]
You should able to decide between
- localstorage
- sessionstorage
- somewhere in the global js context ( could be considered as no-storage (-> result: after page refresh you have to login again))
