### ISSUE TITLE
Path routing broken for some micro-frontends

### ISSUE THREAD

**Issue by y-kkamil** [SAP/luigi#491]
**Description**

If the micro-frontend is configured to use path routing instead of hash routing, Luigi will perform full-page iframe reload instead of letting the micro frontend's router take care of navigation.

**Expected result**

Micro frontend SPA performs navigation without page being reloaded.

**Troubleshooting**

Looks like `luigi.navigate` event is performing `window.location.replace` every time navigation event occurs. This is bad :).

**Comment by kwiatekus** [comment]
detection of mf routing method is required.
if path routing used, use history.push api

**Comment by y-kkamil** [comment]
Related: https://github.com/kyma-project/luigi/issues/452
Needs to be fixed, to make https://github.com/kyma-project/console/issues/750 fully working

**Comment by y-kkamil** [comment]
Fixed for Angular/Vue/React routers in #500 . Bear in mind that merging this solution will break catalog/instances views in Console because of https://github.com/kyma-project/console/issues/798
