### ISSUE TITLE
Invalid auth provider should throw an error

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/luigi#510]
If I accidentally enter a wrong auth provider name `mockAuth2`, no warning or error is shown. 
The checks are not reached due to `isAuthorizationEnabled` returning already before reaching that point in `Authorization.html`.

**Comment by jesusreal** [comment]
Using a wrong auth provider is a developer error. In such case autologin is disabled and we display the anonymous content together with an error alert indicating which is the issue:

![Screenshot 2019-05-22 at 11.36.53.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/fe3b9ad5-2b47-47fb-a8cc-037940b3e81f)
