### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#543]
**Description**

Luigi _pure Vanilla JS_ based applications must be able to run on Internet Explorer 11.

**Reasons**

Increase the potential customer base.

**Comment by maxmarkus** [comment]
I'd like to see then separate bundles for es5 and es6, which can be utilized by

```html
<script type="module" src="main.es6.js"></script>
<script nomodule src="fallback.es5.js"></script>
```
source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Module_fallback

**Comment by jesusreal** [comment]
Thanks to the usage of _browserslist_ we can always know which browsers we are targeting. Currently our legacy bundle supports these browsers: https://browserl.ist/?q=last+1+version%2C+not+dead%2C+%3E+0.2%25
