### ISSUE TITLE
Support fragments in path routing

### ISSUE THREAD

**Issue by magicmatatjahu** [SAP/luigi#55]
**Description**

When `path routing` is used in `Luigi Core`, it is not possible to use anchors/fragments in the website path. This is a very helpful (and old) feature for navigate inside website (especially in the docs). 

**Reasons**

- more transparent url for users: fragments (via anchors) is more readable than `#` or another char in query,
- support anchor navigation in `content` view in `Kyma Console`, and in the future also in `catalog-service` and `instances`.

**Comment by JohannesDoberer** [comment]
Due to our backlog clean up we closed this ticket.
