### ISSUE TITLE
Dropdown functionality for top-right nav nodes

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#574]
**Description**

Add possibility to define navigation nodes in top right header with dropdown children instead of showing children in left navigation.

**Comment by cawmichae** [comment]
Hello, 
Just so we can plan our sprint work accordingly, is it possible to get a rough estimate on this?

**Comment by hardl** [comment]
_Replying to https://github.com/SAP/luigi/issues/574#issuecomment-507335769 by @cawmichae :_
It will be part of the 0.5 release, planned for this week.
