### ISSUE TITLE
Add possibility to open views as modal when clicking on a navigation node

### ISSUE THREAD

**Issue by y-kkamil** [SAP/luigi#603]
**Description**

Currently, when you click on the navigation node, the only possible action, that Luigi can do is to open the viewUrl in the 'content area'. It would be beneficial if there's a possibility to, e.g. open a view as a modal or, even better, to call a function with some custom logic.

**Reasons**

Opening a view as a modal would be needed, for example in: https://github.com/kyma-project/console/issues/754

**Comment by tricky42** [comment]
Not really sure what has been done for this issue? Did you implement something or was it decided not to provide the requested feature?
