### ISSUE TITLE
Lazyloading in context switcher only works the first time

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#612]
**Description**
When setting lazyloadOptions to true, options are fetched on click on context switcher, but only once, then they seem to be cached, although docu says it's not

**Expected result**

Options are refetched everytime i click the context switcher

**Actual result**

Options are fetched only the first time i click the context switcher

**Comment by maxmarkus** [comment]
Current workaround: Dispatch post message with `'luigi.refresh-context-switcher'` as msg, to refresh the cache after adding some value to the context switcher.
