### ISSUE TITLE
Improve existing unit tests

### ISSUE THREAD

**Issue by jesusreal** [SAP/luigi#614]
After #578, as written [here](https://github.com/SAP/luigi/issues/551#issuecomment-498649977) the next action item is 
_There are existing unit tests that are not actually unit tests because calls to other functions are not mocked. An example of that are the unit tests for handleRouteChange method._

#### Acceptance criteria:
- All existing unit tests are mocking any external function being called
- Test cases assertions are updated so that the tests are still meaningful and add value
- Tests are refactored as needed due to actions mentioned above

**Comment by JohannesDoberer** [comment]
Investigate if this ticket is still valid and either work on it or close it.
