### ISSUE TITLE
Context switcher doesn't use label after reload

### ISSUE THREAD

**Issue by dariadomagala** [SAP/luigi#630]
**Description**

I have three values in my context switcher configuration:
```
{
    label: 'I want this label :)',
    pathValue: 'tenant1'
  }, {
    label: 'Tenant 2',
    pathValue: 'tenant2'
  }, {
    label: 'Tenant 3',
    pathValue: 'tenant3'
  }
```
This is displayed properly in the context switcher if I switch tenants using the dropdown.

<img width="192" alt="Screen Shot 2019-07-05 at 09 58 37" src="https://user-images.githubusercontent.com/40663133/60707239-8ff27900-9f0b-11e9-8258-1f339d8c84b3.png">

Problem appears when I reload the page, context switcher reads the value from the path and doesn't use the label assigned to this value.

<img width="193" alt="Screen Shot 2019-07-05 at 09 58 44" src="https://user-images.githubusercontent.com/40663133/60707219-89fc9800-9f0b-11e9-8b69-67d376a0499f.png">

**Expected result**

Context switcher should read the value from the path and look for the label assigned to this value (if exists).

**Actual result**

Context switcher always uses the value from the path.

**Steps to reproduce**

**Troubleshooting**

**Comment by maxmarkus** [comment]
Configuration setting `navigation.contextSwitcher.lazyloadOptions: true` does not fetch options initially so they are not available after a reload. 
Setting it to `false` immediately fetches the options and sets the correct label.
