### ISSUE TITLE
Flaky unit test in CI pipeline

### ISSUE THREAD

**Issue by jesusreal** [SAP/luigi#713]
Investigate why the unit test displayed below is failing from time to time in the CI pipeline and fix the issue if possible.

*Timebox to 1 day*

![Screenshot 2019-08-02 at 12.17.29.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/fad4b957-efc4-4693-9023-ea74cd3a623d)

**Comment by maxmarkus** [comment]
I had this issue also twice locally, which was solved by simply triggering a re-test by saving the file. Unfortunately it's hard to reproduce this error as it seems to be an issue inside jsdom which fails to set up localStorage mock in some situations.
My guess is that a simple retry of the test will fix that.
