### ISSUE TITLE
Would like the ability to edit the sandbox rules 

### ISSUE THREAD

**Issue by cawmichae** [SAP/luigi#744]
**Description**

Would like the ability to edit the sandbox rules when the iFrame is created. (createIFrame function in https://github.com/SAP/luigi/blame/master/core/src/utilities/helpers/iframe-helpers.js)

If this cannot be done, would like allow-top-navigation added to the list of sandbox rules

**Reasons**

I wish to be able to allow-top-navigation. At the moment we have some hyperlinks links in the iFrame which when we click on result in the error:

```
Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://conversionuitest.stage.context.cloud.sap/lounge#/cds/dashboard' from frame with URL 'https://conversionuitest.stage.context.cloud.sap/lounge#/cds/segmentationui'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
```

**Attachments**

![screen](https://user-images.githubusercontent.com/50734654/62881867-a5d43480-bd28-11e9-84d4-480218518fdd.png)

**Comment by JohannesDoberer** [comment]
Hello,
thank you for your ticket.
It will be configurable via settings, which extends the default Luigi sandbox rules. Probably it will be available soon, there is already a pull request.

Cheers,

Johannes
