### ISSUE TITLE
Add ids to iframes

### ISSUE THREAD

**Issue by ronsantiago** [SAP/luigi#758]
**Description**

We would like to be able to have the 'id' attribute of the iframe containing the client application filled in with a unique identifier.

**Reasons**

While trying to perform end-to-end testing of our application, using webdriver.io, we realized that we would need to switch to the application iframe in order to be able to run our tests. Since the iframes are generated dynamically and can change order or index, we would need a more stable way of referencing the iframe containing our application.

**Attachments**

See https://webdriver.io/docs/api/webdriver.html#switchtoframe for more information.

**Comment by jesusreal** [comment]
Hi @ronsantiago,
you can access the active iframe by using `window.Luigi.elements().getCurrentMicrofrontendIframe()` and apply any command to that element as part of your test.

I am closing this issue. In case the suggested solution is not solving your problem, please reopen the issue.
