### ISSUE TITLE
Avoid Luigi "not configured" alarm

### ISSUE THREAD

**Issue by zaheral** [SAP/luigi#768]
**Description**

We are using Luigi-Core version 0.6.1 and it throws an error after 6.5 seconds if Luigi doesn't get any configuration. See screenshots in the attachment chapter that shows the errors. We want an opportunity to control this.

**Reasons**

Our application will be loaded as a compressed version in the browser. This includes also the luigi-core library. Before the luigi-configuration will be set, the user need to authenticate himself in the login page. This is important in our use-case, because the configs are dynamically created from the backend because they are based on the user-permissions.

The problem is that a user can take more than 6.5 seconds until he is done with the authentication. After the timeout is reached, the user gets the confusing alerts and Luigi is not working anymore.

The logic is implements here: https://github.com/SAP/luigi/blob/8b25163b03e11aebf34188ec2789293cc90f0449/core/src/core-api/config.js#L34
As you can see in line 19, the timeout is set on 65000 ms. It would be helpful for us to control this behaviour. We would like to shut this behaviour down, because in our use-case it is not suitable.

**Attachments**

*Error on Screen*
![Screen Shot 2019-08-28 at 13 18 41](https://user-images.githubusercontent.com/26272656/63851864-4bc5a700-c997-11e9-8b2e-4e1ff384895d.png)

*Error on Console*
![Screen Shot 2019-08-28 at 13 18 50](https://user-images.githubusercontent.com/26272656/63851914-6ac43900-c997-11e9-9ca4-121146fbcfdf.png)

**Comment by pekura** [comment]
65000ms are not 6.5 seconds but 65 seconds. But still, valid request to have more control over it, thank you!
