### ISSUE TITLE
Iframe feature policy "allow" required to control

### ISSUE THREAD

**Issue by zaheral** [SAP/luigi#844]
**Description**

Micro-Frontend IFrame includes an app that needs permissions for audio (and later probably also video) communication. By default these features are disabled for child IFrames. This can be enabled with the IFrame attribute "allow" (e.g. <iframe allow="microphone"></iframe>). See more information here:
* https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-allow
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

Please don't mix with sandbox rules. This is something different.

It would be great if we can control this by passing somehow the values for the "allow" attribute in the IFrame. We saw in the code that this is already possible for "sandbox" attribute, but not for the "allow" attribute: https://github.com/SAP/luigi/blob/ca029661f7ba63303d13752d4d2dfa8ec5871271/core/src/utilities/helpers/iframe-helpers.js#L241

Additional requirement that we have is to differentiate the feature policy rules between the Micro-frontends. That means that we should not open the doors for all apps, just for the ones who requires it. The same is also for sandbox rules.
My opinion from a consumer perspective. It would be great if we can specify these rules together with the navigation configuration or at least use the ID's to reference which apps which rules are made.

Controlling the "allow" attribute has a very high priority in our project, because it currently blocks some colleagues to continue with development their task.
Managing the rules for the different micro-frontend apps is a high requirement, but it doesn't blocks anybody.
Therefore, it would be very nice if we get a solution for the first point faster, if possible :)

**Luigi version**
"@kyma-project/luigi-core": "^0.6.3",

**Reasons**
See description

**Attachments**
None

**Comment by zaheral** [comment]
Hi @zarkosimic ,

is this feature now available? If yes, where can I find it?

Best Regards,
Zaher

**Comment by zarkosimic** [comment]
Hi @zaheral ,

Yes, this feature is available by the new release v0.6.5. You can find it and configure in settings of Luigi where you would also define "header", "appLoadingIndicator", "responsiveNavigation", "sideNavFooterText"... just add "allowRules" as a new property with desired one or more options (e.g. allowRules: ['microphone', 'geolocation']). If you have any doubts please let me know.

**Comment by hardl** [comment]
The more fine-grained control will be possible with https://github.com/SAP/luigi/issues/884

**Comment by zarkosimic** [comment]
The feature is available in the documentation under [general settings](https://github.com/SAP/luigi/blob/master/docs/general-settings.md).
