### ISSUE TITLE
Provide a user "avatar" / profile picture

### ISSUE THREAD

**Issue by JoanneLaing** [SAP/luigi#850]
**Description**

We would like to provide users with the ability to display an avatar image, against their user name, in the header.

**Comment by hardl** [comment]
Hi, this is already possible, if you use luigi auth functionality. Just search for "userInfoFn" in our auth documentation https://github.com/SAP/luigi/blob/master/docs/authorization-configuration.md.
If you don't use luigi auth, wait for https://github.com/SAP/luigi/issues/807 to be released ;)
