### ISSUE TITLE
A UI framework without a live demo or screenshots?

### ISSUE THREAD

**Issue by chall3ng3r** [SAP/luigi#872]
**Description**
I looked around a bit and surprised that there's no live demo or even screenshots of the framework in action.

**Reasons**
Before going through the docs, cloning this repo, a developer wants to get a feel of how this thing actually works, and looks.

**Comment by hardl** [comment]
Hi, thanks for your input. Fortunately there is a live demo playground here: fiddle.luigi-project.io, there is just no link yet at the landingpage
