### ISSUE TITLE
Use Svelte components

### ISSUE THREAD

**Issue by maxmarkus** [SAP/luigi#928]
We want to write svelte components for our documentation. Find out how to define the them within markdown as comments, so it does not show any output in normal github markdown viewer.

**Comment by ndricimrr** [comment]
In normal github markdown viewer this should look like: 
```
## Below you can see a representation of our data in graphical format:

# How did you like the graph above ?
```

whereas in the actual lines we would have: 

```
## Below you can see a representation of our data in graphical format:
<!-- svelte:
<script>
     import WonderfulGraph from './WonderfulGraph.svelte'
</script>
 <WonderfulGraph />
 -->
# How did you like the graph above ?
```

The < !--svelte: --> comment would then be rendered through a custom rehype parser as a svelte component.
@maxmarkus is this what you had in mind ?

**Comment by ndricimrr** [comment]
currently svelte's compiler is not intended for our use case, as the components are not rendered the way we want them to. Also as this task is not high priority it is not worth investing more time into it.
